### ISSUE TITLE
[Custom]: Config structure advice

### ISSUE THREAD

**Issue by Balssh** [JaKooLit/Hyprland-Dots#111]
### Description
Hi there, I've been trying out your scripts/config again after like 2 months and I'm pleased to see the improvements. I read that you plan some restructuring of Hyprland config in the future so what I'm gonna write might already be considered, apologies if that's the case. Anyway, I think a more clear delimitation between "user setting" and "general setting" should be implemented. Of course, this can be very subjective, but for example I find it a bit weird for things like mainMod + F to be fullscreen and not in the UserKeybinds.

**Comment by JaKooLit** [comment]
Well, I expected this would raise a concern:

But I will keep it like this for now..

I have been contemplating about just giving the full control to users, but I will be left without a space for any improvement or addition in case :) in which, if that happens, I lose my interest in updating...

**Comment by Balssh** [comment]
Understandable, I see that the userconfigs are imported last so they overwrite the defaults anyway. Thanks for the quick reply <3

**Comment by JaKooLit** [comment]
But on the other hand, I might give the user most of the keybinds...

Ill just keep the workspaces related

**Comment by JaKooLit** [comment]
> Understandable, I see that the userconfigs are imported last so they overwrite the defaults anyway. Thanks for the quick reply <3

yup, thats the idea. the user configs will be source as last....
