### ISSUE TITLE
[Bug]: Keyboard Layout is always returned as "unknown"

### ISSUE THREAD

**Issue by unnamedcrewman** [JaKooLit/Hyprland-Dots#113]
## Bug Report

Keyboard Layout is always returned as "unknown" during install or copying dotfiles

### Description

Any time the scripts (here in Dotfiles or in Fedora-Hyprland install) try to detect the environment (xserver vs. tty) as part of detecting keyboard layout, the layout ends up as unkown.  For example, in `copy.sh, line 82`.

My shell skills are mediocre so I'm not sure, but I think that the problem is the `xserver` check.  It looks to me like the check is based on a non-empty string returned from `$DISPLAY`.

On my system:
 
```
❯ printenv
DISPLAY=:0
```

```
❯ setxkbmap -v
bash: setxkbmap: command not found
```

```
❯ localectl
System Locale: LANG=en_US.UTF-8
    VC Keymap: us
   X11 Layout: us
    X11 Model: pc105
```

I think that the this sends me down the `xserver` route, but my since my system doesn't contain `setxkbmap` the locale testing logic fails.

I've tested the `tty` check in the `copy.sh` script manually, and it works perfectly, which is why I think that I'm getting sent down the `xserver` branch rather than the `tty` branch of the layout test (`line 82`.

### Steps to Reproduce

1. Run `copy.sh` in the Hyprland-Dots directory

# Expected Behavior

The keyboard layout check would come back as "us" which is my confirmed current kb_layout

### Actual Behavior

The keyboard layout check comes back as "unknown"

### Environment

Fedora 39 (Sway)
Hyprland, built from branch main at commit 5f8e4068e51480791dbccbe48e86910e9b3cc881
Laptop - Main Hardware

**Comment by JaKooLit** [comment]
thanks for this.. been months that it was like this and nobody mentioned it lmao


anyway, Ill change something on the next release

**Comment by JaKooLit** [comment]
[copy.sh.tar.gz](https://github.com/JaKooLit/Hyprland-Dots/files/13802638/copy.sh.tar.gz)

Can you check this?

untar and replace the copy.sh in Hyprland-Dots folder

by the way, the dots being pulled from Fedora-Hyprland installer or any of my Distro-Hyprland installer pulls this dots

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/978cb01c7794ca6aabc613810b23698f94fad298#diff-c8e5cd0be63acc3933b0fa5966e3117aed1715314c96779a494910312ac2857f
