### ISSUE TITLE
[Custom]: Short description of the issue

### ISSUE THREAD

**Issue by S4NKALP** [JaKooLit/Hyprland-Dots#114]
### Description

[Change of config-wallpaper.rasi]

### Steps to Reproduce (if applicable)

1. [First Step]
2. [Second Step]
3. [and so on...]

### Expected Behavior

[the text shows at vertical which look not good]

### Actual Behavior

[I have confiure to show element text at bottom of pics]

### Screenshots (if applicable)
![Screenshot_01-Jan_06-23-25_9036](https://github.com/JaKooLit/Hyprland-Dots/assets/98226895/8b45a6f3-8bbe-4884-9945-34b53827337f)

### Rasi file
`/* ---- Configuration ---- */
configuration {
    modi:                       "drun,run";
    font:                       "Fira Code SemiBold 12";
    show-icons:                 true;
    display-drun:               "";
	display-run:                "";
    display-filebrowser:        "";
    display-window:             "";
	drun-display-format:        "{name}";
    hover-select:               true;
    me-select-entry:            "MouseSecondary";
    me-accept-entry:            "MousePrimary";
    window-format:              "{w} · {c} · {t}";
	dpi:						1;

}

/* ---- Load pywal colors (custom wal template) ---- */
@import "~/.config/rofi/pywal-color/pywal-theme.rasi"

/* ---- Window ---- */
window {
    width:						700px;
	/*height:						450px;*/
    x-offset:                   0px;
    y-offset:                   0px;
    spacing:                    0px;
    padding:                    2px;
    margin:                     0px;
    border:                     2px;
    border-color:               @active-background;
    cursor:                     "default";
    location:                   center;
    anchor:                     center;
    fullscreen:                 false;
    enabled:                    true;
    border-radius:              12px;
    border-radius:              12px;
 	background-color:           @background-color;
}

/* ---- Mainbox ---- */
mainbox {
    enabled:                    true;
    orientation:                horizontal;
	padding:					8px;
    /*background-image:           url("~/.config/rofi/.current_wallpaper", width);*/
    children:                   [ "imagebox"];
    border-radius:              12px;
    background-color:      		@active-background;
}

/* ---- Imagebox ---- */
imagebox {
    background-color:           transparent;
    orientation:                vertical;
    children:                   [ "inputbar", "listbox"];
}

/* ---- Listbox ---- */
listbox {
    spacing:                    4px;
    orientation:                vertical;
    children:                   [ "listview" ];
    border-radius:              10px;
    border:                     1px;
    border-color:               @active-background;
	background-color:		    @background;
}

/* ---- Dummy ---- */
dummy {
    background-color:           transparent;
}

/* ---- Inputbar ---- */
inputbar {
    enabled:                    true;
    text-color:                 @foreground;
    spacing:                    10px;
    padding:                    8px;
    border-radius:              10px;
    border-color:               @foreground;
	background-color:		    @background;
    children:                   [ "textbox-prompt-colon", "entry" ];
    border:                     1px;
    border-color:               @active-background;
}

textbox-prompt-colon {
    enabled:                    true;
    expand:                     false;
    str:                        "󰸉 ";
    text-color:                 inherit;
	background-color:			transparent;
}

entry {
    enabled:                    true;
    text-color:                 inherit;
    cursor:                     text;
    placeholder:                "Choose Wallpaper";
    placeholder-color:          inherit;
	background-color:			transparent;
}

/* ---- Listview ---- */
listview {
	enabled:					 true;
	columns:					 4;
	lines:						 3;
	spacing:                     4px;
	dynamic:                     true;
	cycle:                       true;
	scrollbar:                   true;
	layout:                      vertical;
	reverse:                     false;
	fixed-height:                true;
	fixed-columns:               false;
	background-color:            transparent;
	border-radius:             	 10px;
}

/* ---- Element ---- */
element {
    enabled:                    true;
    padding:                    5px;
    margin:                     2px;
    cursor:                     pointer;
    orientation:                vertical;
    background-color:         transparent;
    border-radius:              10px;
    border:                     0px;
}

element normal.normal {
    background-color:           inherit;
    text-color:                 @foreground;
}

element normal.urgent {
    background-color:           inherit;
    text-color:                 @foreground;
}

element normal.active {
    background-color:           inherit;
    text-color:                 @foreground;
}

element selected.normal {
    background-color:           @selected-normal-background;
    text-color:                 @foreground;
}

element selected.urgent {
    background-color:           inherit;
    text-color:                 @foreground;
}

element selected.active {
    background-color:           inherit;
    text-color:                 @foreground;
}

element alternate.normal {
    background-color:           inherit;
    text-color:                 @foreground;
}

element alternate.urgent {
    background-color:           inherit;
    text-color:                 @foreground;
}

element alternate.active {
    background-color:           inherit;
    text-color:                 @foreground;
}

element-icon {
    background-color:            transparent;
    text-color:                  inherit;
    size:                        150px;
    cursor:                      inherit;
    horizontal-align:              0.5;
}

element-text {
    background-color:           transparent;
    text-color:                 transparent;
    cursor:                     inherit;
    horizontal-align:           0.5;
}

/*****----- Message -----*****/
message {
    background-color:           @background;
    margin:						20px 0px 0px 0px;
    border-radius: 				10px;
}

textbox {
    padding:                    15px;
    background-color:      @background;
    text-color:                 @foreground;
}

error-message {
    padding:                    15px;
    border-radius:            20px;
    background-color:      @background;
    text-color:                 @foreground;
}
`

**Comment by JaKooLit** [comment]
Pls dont copy paste since formatting will be change.

Just attach the file here instead

**Comment by JaKooLit** [comment]
never mind... I got it.. Thanks :)
