### ISSUE TITLE
[Feature Request]: # Control RofiBeats using keybinds

### ISSUE THREAD

**Issue by S4NKALP** [JaKooLit/Hyprland-Dots#115]
### Description

[Control RofiBeats using Keybinds and implement in RofiBeats]

### Use Case

[It can be controls by using keybinds which will take lesstime rather using mouse in waybar & can be implemet in RofiBeats, Screenshot is provided ]

### Proposed Solution

[[Music Controller](https://github.com/S4NKALP/hyprland/blob/b25e81d1a3bc0cacd44963159bd681f8aee4639c/config/hypr/scripts/MusicControl.sh) it include features like pause/resume/next/previous/stop the tracks open rofibeats too and this script can be implement in rofibeats. I have my own script where I implement this script [RofiMusic](https://github.com/S4NKALP/hyprland/blob/ca11613433da137d9b8adec0ba693ff53e087c25/config/hypr/scripts/RofiMusic.sh) ] 

### Screenshot
![Screenshot_01-Jan_16-03-18_18565](https://github.com/JaKooLit/Hyprland-Dots/assets/98226895/bbfbff24-a2f6-41c2-9ce5-ba3f2f9c8c22)

**Comment by JaKooLit** [comment]
dude, global keybinds work. You can press play next previous using your keyboard (global keybinds)

it is using playerctl

on using mouse, point the cursor to icon, middle click play/pause, click for previous, right click next

no need to launch rofi for that.
