### ISSUE TITLE
Colors for tty and window borders dont change with randomwallpaper.sh but they do with wallpaper.sh 

### ISSUE THREAD

**Issue by Asteroth2018** [JaKooLit/Hyprland-Dots#117]
Hello. So when i set my wallpaper to randomly change every 15min with your script RandomWallpaper.sh it wokrs ok but it doesnt change colors in my kitty terminal and my border colors. But when i use the Wallpaper.sh one it does change all the colors fine. Ive tried with the Refresh.sh script and with the RefreshNoWaybar.sh one and still the same. Ive noticed in the code that it does have the pywal refresh because it does it through the Refresh.sh script so it should work on paper as i see the code (but maybe im missing something). And I really dont know why it doesnt work. And I just wanted to say that the work youre doing is awesome!!!

**Comment by JaKooLit** [comment]
I just edited the FAQ

https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-pywal-color-changed-on-tty-or-kitty
