### ISSUE TITLE
Issue with new kitty terminal

### ISSUE THREAD

**Issue by Epineph** [JaKooLit/Hyprland-Dots#12]
First thanks, been using your scripts for a while. However, I just noticef that you made the change to get kitty as the new terminal instead of foot. In the config file for kitty, there is no keybimd section to change things such as clipboard copy and paste. 

How can I deal with this issue (I much prefer the pre-newest update (the super+d command menu is confusing with the background and then the thing about making changes to keybinds.

The colours when using zsh in kitty also look slightly off, like unsaturated. Never experienced that with foot.
Thanks,
Ep

**Comment by JaKooLit** [comment]
https://youtu.be/yaVurRoXc-s?si=puI59E03IC67ulE8

I have mentioned on that video about disabling pywal colors on kitty

kitty configuration that I have set in there is only addition.

When you load kitty, it will pull the default configuration which is located here

/usr/share/doc/kitty/kitty.conf

https://wiki.archlinux.org/title/Kitty

and keybinds, I have not change keybinds.. my default launcher have always been super d

you can change the keybinds through Keybinds.conf

**Comment by Epineph** [comment]
Thank you for the response. Your scripts have been vital for me for and are by far the best out there. I am glad that you keep working on it, and my question is probably more indicative of my limited knowledge with regards to configurations. 

Earlier, in the ~/.config/foot/foot.ini I used to change the keybinds there. Can the same syntax be used and set in ~/.config/hypr/configs/Keybinds.conf? 

Since I just did a clean reinstall (I am working on a guide to do installations based on the zfs-filesystem), I cannot remember how it was set in the foot.ini file. I am relatively new to gitub, so I admit that it might just be a lack of knowledge and confusion when you made your last change. 

Perhaps, if you do not mind, if I wanted to be able to use control+c and control+v for clipboard copy and paste, respectively, where should it be done and if you could show me how to do that (I watched some of your youtube videos, but I am still not completely aware of how hyprland, wofi and all the other packages interact, and whether settings in one locations can conflict with the settings at other locations, or if some file and its configurations supercede others).

Anyways, if you don't mind answering that question and perhaps guide me how, if it is possible, to retrieve earlier versions, that would be great. I would like to keep the updated file and if you can show me how to do the configuration described above - so that it would work in the kitty terminal, that would be awesome.

Thanks for your reply and keep up the good work. I have been relying in your scripts for over a month now and I absolutely love it.


Thank you,

**Comment by Epineph** [comment]
Nevermind, your first question guided me to the correct place.


I found it in the doc and inserted the following in the kitty.conf in the home subdirectory:

map ctrl+c copy_to_clipboard

map ctrl+v paste_from_clipboard


So it works now. Thank you!

**Comment by JaKooLit** [comment]
https://sw.kovidgoyal.net/kitty/conf/

there is a part about the clipboards here..

And also, if you still want to use foot, you can of course.

You just need to edit primary the 

Keybinds.conf. Replace the kitty with foot..

So once you press super enter, it will open the foot instead of kitty

and then you can check the remaining scripts and waybar modules..

if you dont want to do that  just let the kitty installed and use foot as your main tty

**Comment by JaKooLit** [comment]
so can close this issue?
