### ISSUE TITLE
Need Help regarding extracting your waybar theme/layout & wallpaper Switching scripts from your dots

### ISSUE THREAD

**Issue by muneebusmani** [JaKooLit/Hyprland-Dots#121]
Hey There ! 
i used your hyprland dots previously but due to (Hyprland's own) issues , i migrated to swaywm, but i need help regarding where to find your scripts for switching wallpapers, and waybar theme and layout

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/tree/main/config/hypr/scripts
