### ISSUE TITLE
[Feature Request]: Apply gtk style to flatpak apps

### ISSUE THREAD

**Issue by nr23730** [JaKooLit/Hyprland-Dots#122]
### Description

Right now Flatpaks use default light theme. This is a minor issue and this inconsistency can be easily fixed by providing two overrides. I see that https://github.com/JaKooLit/Hyprland-Dots/blob/b70c149d96c7fed3c4b364fdf8f8ae7c1172b069/config/hypr/scripts/DarkLight.sh#L152
already points in this direction. However this might not be enough for all apps. 
Tested with Evolution Mail on Fedora 39.

### Use Case

You may have programs installed that use the GTK framework are being distributed via flatpak.

### Proposed Solution

Check if flatpak is installed and then execute
```
flatpak --user override --filesystem=$HOME/.themes
flatpak --user override --filesystem=$HOME/.icons
```

### Alternatives

The user may be asked if this patch should be applied.

**Comment by JaKooLit** [comment]
![swappy-20240106-234221](https://github.com/JaKooLit/Hyprland-Dots/assets/85185940/efbdc5a4-2973-4129-99e5-77d31d1bc281)

This is ok?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/876a392a16bbdea0b16eb28a21b00819d12b9f1a

Will be included in the next publish

https://github.com/JaKooLit/Hyprland-Dots/wiki/TIPS#-flatpak-gtk-themes-dark--light


Added as well in the Hyprland-Dots wiki (TIPS)

Thanks for that
