### ISSUE TITLE
[Bug]: Wrong variable name for UserConfig directory

### ISSUE THREAD

**Issue by nr23730** [JaKooLit/Hyprland-Dots#124]
### Description

This is declared as:

https://github.com/JaKooLit/Hyprland-Dots/blob/b70c149d96c7fed3c4b364fdf8f8ae7c1172b069/config/hypr/UserConfigs/Startup_Apps.conf#L5

but referenced as 

https://github.com/JaKooLit/Hyprland-Dots/blob/b70c149d96c7fed3c4b364fdf8f8ae7c1172b069/config/hypr/UserConfigs/Startup_Apps.conf#L9
..
https://github.com/JaKooLit/Hyprland-Dots/blob/b70c149d96c7fed3c4b364fdf8f8ae7c1172b069/config/hypr/UserConfigs/Startup_Apps.conf#L35

### Expected Behavior

Tools where this variable is used are working properly.

### Actual Behavior

Tools where this variable is used to not work properly (e.g. wlsunset, automatic wallpaper change)

**Comment by JaKooLit** [comment]
thanks bro

Cant believe I missed that

https://github.com/JaKooLit/Hyprland-Dots/compare/v2.2.3-hotfix...v2.2.3-hotfix2

**Comment by nr23730** [comment]
You're welcome. 
By the way: Thank you so much for your hard work on the install scripts and dot files! They're really great to get started.
