### ISSUE TITLE
Clipboard : Control + Delete to remove enty

### ISSUE THREAD

**Issue by S4NKALP** [JaKooLit/Hyprland-Dots#129]
If you want to delete or wipe whole history then edit line 21 to cliphist wipe. By pressing CTRL + Delete can do this.
As the scipt is provided 

[ClipManager](https://github.com/S4NKALP/hyprland/blob/28d3a2c1d221103406e2152117f6b06cb7a424d4/config/hypr/scripts/ClipManager.sh) 

And I have another scipt where submenu are integrated as shown in picture
The Script [ClipManager.sh.zip](https://github.com/JaKooLit/Hyprland-Dots/files/13855353/ClipManager.sh.zip)

![Screenshot_08-Jan_05-46-58_4294](https://github.com/JaKooLit/Hyprland-Dots/assets/98226895/b8dd61d5-0adc-41c7-9789-1e74e9d7f3b7)

**Comment by JaKooLit** [comment]
thanks.. ill see what I will come up with...
