### ISSUE TITLE
about cava

### ISSUE THREAD

**Issue by kimuxer** [JaKooLit/Hyprland-Dots#131]
![Screenshot_08-1月_20-02-31_8281](https://github.com/JaKooLit/Hyprland-Dots/assets/4003419/d6360ca1-66a4-4726-960f-b0b209d2ec40)

Hey JaKooLit 
I don't know if this is a BUG or not
It seems to be because I pressed CTLR+ALT+W many times to switch wallpaper when listening to music on rofibeats.
There are a lot of cava in btop, occupying some memory

**Comment by JaKooLit** [comment]
good catch and thanks alot for the PR.

**Comment by momcilovicluka** [comment]
Thank you. Happy to help
