### ISSUE TITLE
[Bug]: Discord doesnt open

### ISSUE THREAD

**Issue by Landixbtw** [JaKooLit/Hyprland-Dots#139]
## Bug Report
Discord doesn't open. When trying to open via %mainMod d or via console: discord. 
### Description

I downloaded hyprland with the script. Everything works fine looks good. But discord doesn't open.  (will put console output down there)

### Steps to Reproduce 
1. Have discord installed with the vencord extension.
2. Install Hyprland with the install script. 
4. Try to open discord either via command line or App menu

### Expected Behavior

Discord opens.

### Actual Behavior

Nothing happens. If you try to launch it via the command line. 

### Screenshots
```
[Vencord] Starting up...
[Vencord] Loading original Discord app.asar
Discord 0.0.41
Quitting secondary instance.
blackbox: 2024-01-24T14:01:36.215Z 0 

----------------------------------------------
blackbox: 2024-01-24T14:01:36.221Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.41"}, modulepath: /home/ole/.config/discord/0.0.41/modules
```

### Environment

- Linux Distro: [EndeavourOS]
- Linux Version, output of `uname -a`: Linux endeavour 6.7.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sun, 21 Jan 2024 22:14:10 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 03ebbe18ed8517ee22591eac82cd54322f42cb7d  (props: bump ver to 0.34.0).
Date: Mon Jan 1 12:03:15 2024
Tag: v0.34.0

flags: (if any)

- Installation Environment: [On a removable SSD, NO VM]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

I have not tried it with Other discord apps. But I dont think it'll change much. On KDE Plasma all works fine. 
Overall its a really nice config tho. Only the mouse cursor is a bit fast.

**Comment by Landixbtw** [comment]
Fixed it.

**Comment by lntcT** [comment]
> Fixed it.

It is helpful to provide your solution so others can apply them.

**Comment by Landixbtw** [comment]
> > Fixed it.
> 
> 
> 
> It is helpful to provide your solution so others can apply them. 

Solution was I am stupid. Discord was open in the background but I didnt see it
