### ISSUE TITLE
[Bug]: weird notification

### ISSUE THREAD

**Issue by ANRY17** [JaKooLit/Hyprland-Dots#140]
i instaled fresh archlinux hyprland on my laptop and got this weird notifications

![Screenshot_25-Jan_21-14-29_18770](https://github.com/JaKooLit/Hyprland-Dots/assets/90314986/3a3bc29e-2b5b-4974-8008-b9131d43d490)

i installed 2 times and still got that

**Comment by JaKooLit** [comment]
what is weird about it?

**Comment by ANRY17** [comment]
text not centered and font size too small

**Comment by JaKooLit** [comment]
its swaync.... been trying to center about it
