### ISSUE TITLE
[Bug]: Rofi (app launcher) not installed by arch install script

### ISSUE THREAD

**Issue by lntcT** [JaKooLit/Hyprland-Dots#141]
Rofi (App Launcher) not being installed by the arch install script.

### Steps to Reproduce

1. Install from the Arch script

### Expected Behavior

install rofi as the app launcher 

### Actual Behavior

rofi was not installed

### Environment

- Linux Distro: EndeavourOS
- Linux Version: 6.7.1-arch1-1
- Hyprland Version, output of `hyprctl version`: , output of `uname -a`:
- Installation Environment: Bare Metal

### Additional Information

Fixed by installing rofi using `yay -S rofi`

**Comment by JaKooLit** [comment]
You should install the rofi-wayland instead.
