### ISSUE TITLE
[Custom]: how to make ncurses default in cava 

### ISSUE THREAD

**Issue by NischalDawadi** [JaKooLit/Hyprland-Dots#154]
The config of cava changes everytime I change the wallpaper.
So i followed the instructions you have given in solving cava issue but still I have to manually change cava config everytime I change wallpaper

**Comment by JaKooLit** [comment]
you need to change this instead

https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/wal/templates/cava-colors


if you dont want the cava config to be touched whenever you change wallpaper, then delete line 40 of

https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/scripts/Refresh.sh
