### ISSUE TITLE
[Bug]: Short description of the issue

### ISSUE THREAD

**Issue by sachu0dev** [JaKooLit/Hyprland-Dots#161]
### randomly red error bar came on top of the screen
'
![swappy-20240218-225236](https://github.com/JaKooLit/Hyprland-Dots/assets/154815993/0152c0f3-c5eb-4094-9f76-ba9f4798410f)

**Comment by atjanov** [comment]
I think you should describe what you were doing before the error appeared and show information from the specified lines.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/releases/tag/v2.2.5

**Comment by JaKooLit** [comment]
> Solution: just get rid of the extra ##### in hyperland config file just leave single # in comments

thats why I attached my committed clean up code for guidance
