### ISSUE TITLE
[Bug]: Cannot change background color in swaylock

### ISSUE THREAD

**Issue by barbas66** [JaKooLit/Hyprland-Dots#164]
### Description

As per title,

no matter the color I choose as background in swaylock config file (pic. 1), the screen keeps having a withish color (pic. 2).

### Steps to Reproduce

1. Edit swaylock config file ($HOME/.config/swaylock/config)
2. Reboot system
3. Lock screen through waybar button

### Expected Behavior

A different background color for lock screen (see pic. 3) - Result of command: #swaylock -c FF0000FF

### Actual Behavior

[What actually happened?]

Background color is unchanged

### Screenshots

Pic. 1

![Screenshot_19-feb_16-01-09_28995](https://github.com/JaKooLit/Hyprland-Dots/assets/108096320/819880dc-2daa-47c6-bbdf-ac195ab0f50d)

Pic. 2

![IMG20240219160425](https://github.com/JaKooLit/Hyprland-Dots/assets/108096320/a79aae0d-a3f9-4e4c-980e-19bed0f0e9c7)

Pic. 3

![IMG20240219162250](https://github.com/JaKooLit/Hyprland-Dots/assets/108096320/a45d6622-6215-4ee2-8d6a-9e708e1ab6f4)

### Environment

Distro: EndeavourOS
Kernel: 6.7.5-arch1-1
Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0)
Installed on main hardware

**Comment by JaKooLit** [comment]
can you state what you edited in ~/.config/swaylock/config ?

**Comment by barbas66** [comment]
Here you go, hope it's the right parameter to set.
![IMG_20240219_181119](https://github.com/JaKooLit/Hyprland-Dots/assets/108096320/38f3b4cb-3b00-4b62-a504-5a37bc58d333)

**Comment by JaKooLit** [comment]
https://github.com/swaywm/swaylock/blob/master/swaylock.1.scd

I believe you should switch to swaylock instead of swaylock effects

from the link it looks it supports the color options

on the swaylock effects, it does not seem to have function for color only as background.. although I could be wrong

**Comment by JaKooLit** [comment]
https://github.com/jirutka/swaylock-effects

**Comment by barbas66** [comment]
Thanks.

For the time being I'll be using using the package swaylock.

Cheers!
