### ISSUE TITLE
[Bug]: GameMode shortcut incorrect behaviour

### ISSUE THREAD

**Issue by Davido264** [JaKooLit/Hyprland-Dots#168]
### Description

Honestly, I don't know if this just happens to me. But I post it here in case it is not. When I press `SUPER+SHIFT+G`, Game mode doesn't get activated, and I only get the notification saying that Gamemode has been disabled.

### Steps to Reproduce

1. Press `SUPER+SHIFT+G`

### Expected Behavior

Activates Game mode, and if it is already activated, deactivate it.

### Actual Behavior

Not activating it and showing a notification telling its already activated.

### Environment
- Linux Distro: Fedora 39 Sway
- Linux Version, output of `uname -a`:  
  `Linux aspiref5 6.7.6-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Feb 23 18:27:29 UTC 2024 x86_64 GNU/Linux`
- Hyprland Version, output of `hyprctl version`: 0.36.0
- Installation Environment: On The Main Hardware

### Additional Information
Digging into the script, I find this gets executed: 
```bash
HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')
```
But, when I run `hyprctl getoption animations:enabled`, the output is this:
```
int: 1
set: true
```
So, the `awk` command is capturing the second line (which allways will output "true") and not the first one, which is checked to be "1" by the script. 

I fixed in my machine by changing `awk 'NR==2{print $2}'` to `awk 'NR==1{print $2}'` :3

When I did that I found another error, that is that animations don't get reenabled when I disable gamemode, that turned out to be a `exit` command at the end of the `else` branch on the script, and `hyprctl reload` never executes. I solved it by removing the `exit` command on the `else` branch :3

**Comment by JaKooLit** [comment]
thanks for this.. could you pls report to hyprland github page as this is literally just a modified version of this script

https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/

look for game mode.

seems like this was broken from latest update

**Comment by Davido264** [comment]
thanks for the response, I checked the script on the Hyprland wiki and it seems they fixed the issue with `awk 'NR==1{print $2}'`. So I'm going to close this issue
