### ISSUE TITLE
[Feature Request]: Theme patcher/ Custom Themes

### ISSUE THREAD

**Issue by CptNemo1337** [JaKooLit/Hyprland-Dots#170]
Hi, I think you've done a great job, I'm very impressed. 
I would like to try adding my own themes, but I find it difficult to get through your configuration as a beginner. 
A colleague has set up a similar project to yours, there it is pretty well explained how to add your own themes including folder structure etc. (https://github.com/prasanthrangan/hyprdots/wiki/Theming) 

I would be very happy if you could create a similar post on how to add a new rice to your Hyprland ecosystem. 
I like your base the best so far from everything I've seen and I'd love it if there was a reference guide on how to implement a new theme or if you could simplify the process (like prasanthrangans Themepatcher)

Thanks in advance

**Comment by xsghetti** [comment]
Step 1. Take a css file from each category
Step 2. Rename to your theme
Step 3. Change color palette
Step 4. ???
Step 5. Profit. 

I recommend learning the ins and outs of hyprland before opening something that isn’t considered “an issue”. This is lack of knowledge and looking for someone to hold your hand.
