### ISSUE TITLE
[Bug]: Specific clock modules will not appear

### ISSUE THREAD

**Issue by playtrack44** [JaKooLit/Hyprland-Dots#178]
### Description

[On a fresh install of the arch dotfiles, the TOP LEFT and TOP RIGHT waybar configs do not sure the clock module and appears blank.]

### Steps to Reproduce

1. [Install the arch specific install script via GitHub]
2. [boot into the environment after the installation is complete ]
3. [SUPER + alt + b and choose either TOP LEFT or TOP RIGHT configs, bug will be present that clock module does not show for those, but other do]

### Expected Behavior

[For the clock module to appear like the other configs in the dotfiles ]

### Screenshots

![bug report](https://github.com/JaKooLit/Hyprland-Dots/assets/161546365/a75ef719-f5ce-46b8-ac4e-73f32592c58a)

### Environment

- Linux Distro: EndeavorOS

- Linux Version, output of `uname -a`: Linux  6.8.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 16 Mar 2024 17:15:35 +0000 x86_64 GNU/Linux

- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch HEAD at commit 84ab8d11e8951a6551d1e1bf87796a8589da6d47  (props: bump ver to 0.35.0).
Date: Mon Feb 5 01:59:02 2024
Tag: v0.35.0

- Installation Environment: Daily driver environment ( non virtualization of WM )
- Other info: Resolution(s) = 3840x2160 , 160hz, 1920x1080 , 240hz

**Comment by JaKooLit** [comment]
thanks for this. Ill look into it from time to time. I cant promise too soon but Ill leave this open to serve as reminder for me.

thanks

**Comment by JaKooLit** [comment]
![Uploading Screenshot_29-Mar_05-35-54_19951.png…]()
