### ISSUE TITLE
computer goes to sleep after a few seconds when opening from sleep mode

### ISSUE THREAD

**Issue by 2Senn** [JaKooLit/Hyprland-Dots#185]
### Description

When starting hyprland from a cold boot everything works fine. However if i close the lid of my laptop and then open it back up again, it stays on for a few seconds then goes into sleep mode and this continues unless I fully restart

### Steps to Reproduce

1. go into sleep mode by closing laptop lid
2. start it again (no login screen shows)
3. wait around 10-30s and it goes to sleep

### Expected Behavior

...

### Environment

- Linux Distro: fedora 39
- Linux Version, output of `uname -a`: Linux fedora 6.7.9-200.fc39.x86_64 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: Hyprland, built from branch main at commit 356414639fc06ace7045236ec41d673342981057
- Installation Environment: main hardware

**Comment by JaKooLit** [comment]
sorry but I DID not configure any sleep function on my dots

**Comment by 2Senn** [comment]
any clue what the issue might be though?

**Comment by JaKooLit** [comment]
check your fedora settings. Could be set by default on your gnome or plasma...

if not, there is systemd settings.

https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate
