### ISSUE TITLE
[Feature Request]: Make rofi searches case insensitive

### ISSUE THREAD

**Issue by myryk31415** [JaKooLit/Hyprland-Dots#191]
### Description

Just a minor annoyance but when searching in the custom rofi menus (e.g. $mainmod + e : config files) it is case sensitive.
This doesn't apply for the normal app selection menu, which is already case insensitive.

### Proposed Solution

Add -i to the rofi command to make it case insensitive

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/69ffeffbfc1f8464219f03260c529230d1a36344

will be pushed in Main on next release

**Comment by myryk31415** [comment]
:D
