### ISSUE TITLE
[Feature Request]: Networkmanager-applet

### ISSUE THREAD

**Issue by myryk31415** [JaKooLit/Hyprland-Dots#192]
### Description

Something similar to the blueman-manager but for networks would be great, first time installing i got kinda stuck on how to connect to my wifi. 

### Use Case

[Describe how this feature would be useful to you or to other users of the project.]

### Proposed Solution

nm-applet would work. Adding: >"on-click": "nm-connection-editor"< to "network" and "network#speed"

### Alternatives

there is probably other GUIs that would work as well.

### Additional Information

I used the opensuse tumbleweed install script.

**Comment by JohnRTitor** [comment]
Is not this what you are looking for? 
![swappy-20240401-190958](https://github.com/JaKooLit/Hyprland-Dots/assets/50095635/930bffeb-096d-482b-bea8-32b84698c852)

**Comment by myryk31415** [comment]
yeah but there is now way to connect to a new wifi network this way, is there? I checked the modules file and there are no on-click events, so its only visual feedback right

**Comment by JaKooLit** [comment]
I have been trying to do but I couldnt figure out a standalone gui for network manager. If you have or if you know a project, pls let me know

**Comment by myryk31415** [comment]
The module available on most layout just shows that I am disconnected, hovering over the icon just shows the text disconnected. Clicking on it doesn't do anything. Is that different for you? 

```
network": {
    "format": "{ifname}",
    "format-wifi": "{icon}",
    "format-ethernet": "󰌘",
    "format-disconnected": "󰌙", 
    "tooltip-format": "{ipaddr}  {bandwidthUpBytes}  {bandwidthDownBytes}",
    "format-linked": "󰈁 {ifname} (No IP)",
    "tooltip-format-wifi": "{essid} {icon} {signalStrength}%",
    "tooltip-format-ethernet": "{ifname} 󰌘",
    "tooltip-format-disconnected": "󰌙 Disconnected",
    "max-length": 50,
    "format-icons": ["󰤯","󰤟","󰤢","󰤥","󰤨"],
},
```
There is now way to interact with it thats why I proposed adding smth like this:
`
    "on-click": "nm-connection-editor"
`

**Comment by myryk31415** [comment]
nm-connection-editor is part of nm-applet, the page where you can select the wifi etc

**Comment by JaKooLit** [comment]
Im fully aware of that

> The module available on most layout just shows that I am disconnected, hovering over the icon just shows the text disconnected. Clicking on it doesn't do anything. Is that different for you?
> 
> ```
> network": {
>     "format": "{ifname}",
>     "format-wifi": "{icon}",
>     "format-ethernet": "󰌘",
>     "format-disconnected": "󰌙", 
>     "tooltip-format": "{ipaddr}  {bandwidthUpBytes}  {bandwidthDownBytes}",
>     "format-linked": "󰈁 {ifname} (No IP)",
>     "tooltip-format-wifi": "{essid} {icon} {signalStrength}%",
>     "tooltip-format-ethernet": "{ifname} 󰌘",
>     "tooltip-format-disconnected": "󰌙 Disconnected",
>     "max-length": 50,
>     "format-icons": ["󰤯","󰤟","󰤢","󰤥","󰤨"],
> },
> ```
> 
> There is now way to interact with it thats why I proposed adding smth like this: `"on-click": "nm-connection-editor"`

a favor then, I am not on my system now, can you add this then and see if that is working?

**Comment by myryk31415** [comment]
that was the answer to the other person. I added it to my setup, it works, but I just noticed an Issue, you can only add wifi networks manually in the connection editor, available networks are only shown when clicking on the system tray icon.
I'll have a look wether i can find a workaround or a better gui

**Comment by myryk31415** [comment]
rofi-network-manager:
https://github.com/P3rf/rofi-network-manager?tab=readme-ov-file#features

On Tumbleweed it was available as package, otherwise there is a script as well.
Does close with escape, not the hyprland keybind for closing windows. Has a different look too, but I'd say its definitly better than not having any gui.

**Comment by JohnRTitor** [comment]
> The module available on most layout just shows that I am disconnected, hovering over the icon just shows the text disconnected. Clicking on it doesn't do anything. Is that different for you?

Yes. Clicking on it brings up this menu.

**Comment by JohnRTitor** [comment]
right there is no on click event, but clicking on it brings up the menu? Weird. Anyways, I am on NixOS with network manager enabled. And I do use a lot of other packages. Maybe that's related?
```
"network": {
    "format": "{ifname}",
    "format-wifi": "{icon}",
    "format-ethernet": "󰌘",
    "format-disconnected": "󰌙", 
    "tooltip-format": "{ipaddr}  {bandwidthUpBytes}  {bandwidthDownBytes}",
    "format-linked": "󰈁 {ifname} (No IP)",
    "tooltip-format-wifi": "{essid} {icon} {signalStrength}%",
    "tooltip-format-ethernet": "{ifname} 󰌘",
    "tooltip-format-disconnected": "󰌙 Disconnected",
    "max-length": 50,
    "format-icons": ["󰤯","󰤟","󰤢","󰤥","󰤨"]
},
```

**Comment by myryk31415** [comment]
hmm thats weird. maybe its not the network module but a different one? the name should be in the config as well. (this time actually in the config file and not the modules one i messed up the names lol)

**Comment by JohnRTitor** [comment]
It's the "tray" module. Can't find where it's defined though.

**Comment by myryk31415** [comment]
Ah that makes sense. Thats some networkmanager gui that gets started somewhere on ur system and then sits in the tray, this works for me as well. But i had to set it up manually. So would be great if there was a way to do it with the network module directly, eg with the rofi-network-manager.

**Comment by JohnRTitor** [comment]
Yes, then another network manager applet would be redundant, since both would show up in Waybar.

**Comment by myryk31415** [comment]
yes but then it should at least be installed and executed on startup, I didnt have any way to configure my wifi at first (on the cli ofc but I didnt know how to, that was kinda discouraging after installing)

**Comment by JohnRTitor** [comment]
Yes, installing additional system components is out of scope for this discussion. User should do it themselves.

**Comment by myryk31415** [comment]
Okay great, idk for some reason it didnt show up for me, whatever.
