### ISSUE TITLE
Some characters of waybar are missing and not rendering

### ISSUE THREAD

**Issue by YuliangXiaoYLX** [JaKooLit/Hyprland-Dots#216]
### Description

Some characters or icons are missing or not rendering in Waybar.

### Steps to Reproduce

1. Hyprland
2. Select Waybar layout: [TOP] Default

### Expected Behavior

The icons and characters are displayed successfully

### Actual Behavior

Those are missing and not rendered correctly!

### Screenshots

![image](https://github.com/JaKooLit/Hyprland-Dots/assets/70731556/983d27dc-ade5-4cf1-a377-622753d96d8a)

### Environment

Linux Distro: ```ArchLinux``` 
Linux Version: ```6.8.7-arch1-1```
Hyprland Version: ```Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759 (props: bump version to 0.39.1)```
Installation Environment: ```On The Main Hardware```
Display Resolution: ```Monitor 1: 3840x2160@144; Monitor 2: 2560x1440@75```

**Comment by JaKooLit** [comment]
must be some fonts conflicting with it.

Have you installed any fonts?

can you show here
ls /usr/share/fonts
ls /usr/local/share/fonts
ls ~/.local/share/fonts

**Comment by mikami520** [comment]
> must be some fonts conflicting with it.
> 
> Have you installed any fonts?
> 
> can you show here ls /usr/share/fonts ls /usr/local/share/fonts ls ~/.local/share/fonts
Hi @JaKooLit Thanks for your response and great work on dot files.
Here is the output:
```bash
ls /usr/share/fonts
adobe-source-code-pro  cantarell  droid  encodings  gnu-free  gsfonts  liberation  noto  OTF  TTF  wenquanyi
```
```bash
ls /usr/local/share/fonts
ls: cannot access '/usr/local/share/fonts': No such file or directory
```
```bash
ls ~/.local/share/fonts
ls: cannot access '/home/chris/.local/share/fonts': No such file or directory
```

**Comment by JaKooLit** [comment]
can you try to install / reinstall

sudo pacman -S ttf-jetbrains-mono-nerd


and then reboot

**Comment by mikami520** [comment]
> can you try to install / reinstall
> 
> sudo pacman -S ttf-jetbrains-mono-nerd
> 
> and then reboot

The problem was solved. Thank you!
