### ISSUE TITLE
Errors while installing

### ISSUE THREAD

**Issue by tahadnan** [JaKooLit/Hyprland-Dots#235]
**ERROR1:** libjpeg62-turbo-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR2:**l  ibgulkan-0.15-0 failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
[33m[NOTE](B[m Installing libgulkan-dev ...
**ERROR3:** libtomlplusplus-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR4:** libvkfft-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR5:** libvulkan-volk-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR6:** libxcb-composite0-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR7:** libxcb-cursor-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(
**ERROR8:** vulkan-validationlayers-dev failed to install :( , please check the install.log. You may need to install manually! Sorry, I have tried :(

**Comment by JaKooLit** [comment]
distro?

**Comment by tahadnan** [comment]
@JaKooLit  Ubuntu 24.04 LTS bro
and thanks for your stunning work btw <3

**Comment by JaKooLit** [comment]
> @JaKooLit Ubuntu 24.04 LTS bro and thanks for your stunning work btw <3

ah.. I think you can just ignore that since some of this packages is for debian-trixie only.. 

does it work?

**Comment by tahadnan** [comment]
@JaKooLit  No bro it didn't, I rebooted and it doesn't qhow "Hyprland" in the list with ubuntu and Xorg ubuntu

**Comment by JaKooLit** [comment]
ok... kindly attach the full Install-Logs here

**Comment by tahadnan** [comment]
[Installogs.zip](https://github.com/JaKooLit/Hyprland-Dots/files/15210214/Installogs.zip)
Sorry bro if it's messy I've ran it three times 😅

**Comment by tahadnan** [comment]
@JaKooLit  any help will be much appreciated I really want to use this masterpiece

**Comment by JaKooLit** [comment]
[install-04-160800_hyprland.log](https://github.com/JaKooLit/Hyprland-Dots/files/15210223/install-04-160800_hyprland.log)

hyprland was not installed...

I have updated the script 

You can rename first the Debian-Hyprland folder 


then redownload the repo
git clone --depth=1 https://github.com/JaKooLit/Debian-Hyprland.git ~/Debian-Hyprland
cd ~/Debian-Hyprland
./install-scripts/hyprland.sh

**Comment by tahadnan** [comment]
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/110527009/3a48e72b-f1b3-46b1-a510-4d640a089266)
it reaches 92% and suddenly close

**Comment by JaKooLit** [comment]
dont cd in the install-scripts

do as I type

you have to launch outside the install-scripts folder 🙄

**Comment by JaKooLit** [comment]
![Screenshot_20240505_012929_Samsung Internet](https://github.com/JaKooLit/Hyprland-Dots/assets/85185940/250dd007-9814-4f85-8f5c-872264332ef2)

**Comment by tahadnan** [comment]
Sorry, I'm not really familiar with such process

**Comment by tahadnan** [comment]
@JaKooLit  thanks bro it works just fine! but most of the shortcuts aren't working and I want to keep default icons on the normal ubuntu, is it possible (Sorry if I bothered you a lot)

**Comment by JaKooLit** [comment]
> @JaKooLit thanks bro it works just fine! but most of the shortcuts aren't working and I want to keep default icons on the normal ubuntu, is it possible (Sorry if I bothered you a lot)

You can use the nwg-look (GTK Settings) to set the icons

**Comment by tahadnan** [comment]
@JaKooLit sank youuuuuuu bro
