### ISSUE TITLE
every time wallpaper changes, layout gets reset back to master from dwindle

### ISSUE THREAD

**Issue by dhelgerson** [JaKooLit/Hyprland-Dots#245]
### Description

see title

### Steps to Reproduce

install project.
switch to dwindle
wait

### Expected Behavior

remain dwindle

### Actual Behavior

switches back to master

**Comment by JaKooLit** [comment]
![swappy-20240507-203936.png](https://github.com/JaKooLit/Hyprland-Dots/assets/85185940/4aa0f43f-430b-4cfa-b9ea-c4128ede407d)

kindly change the settings to dwindle from master to make it permanent

**Comment by JaKooLit** [comment]
did you change to dwindle?

**Comment by JaKooLit** [comment]
anything here? done?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/06739c6b1fd121e9d3c53f907f4af4a096cb9a3b

On next release, default will be dwindle layout
