### ISSUE TITLE
[Bug]: Waybar stopped showing my workspaces

### ISSUE THREAD

**Issue by sdebets** [JaKooLit/Hyprland-Dots#249]
Waybar stopped showing my workspaces. Manual startup gives the following error:

[warning] module hyprland/workspaces#4: Disabling module "hyprland/workspaces#4", Error parsing JSON: * Line 1, Column 1
  Syntax error: value, object or array expected.

The  only thing changed since last login was updating to hyprland 0.4.

**Comment by JaKooLit** [comment]
as I mentioned above, its needs to update waybar. Can confirm this because I have compiled waybar from soirce
