### ISSUE TITLE
Add NVidia Optimus support

### ISSUE THREAD

**Issue by TsugikuniVi** [JaKooLit/Hyprland-Dots#25]
Hello!

I recently watched your Arch Hyprland video and I liked it. However I faced a problem since I chose NVidia Hyprland, and it consumed too much power. 
I also commented about this in your video, to which you responded. I tried to follow it but, but since I was new Linux as a whole, I bricked my install and SDDM wouldn't load me in anymore. 

So, I reinstalled it WITHOUT NVidia Hyprland, and it doesn't consume as much power. But now, I have a different problem, which is that my apps don't see my NVidia GPU, even though it is visible through `lspci`. 
After this I found out about NVidia Optimus, but I was very confused even though it seemed simple. Please add NVidia Optimus to your install script.

(PS I'm now trying to install EndeavourOS with Hyprland but I don't know what to do 😅. Please make a video on this along with Optimus.)

Love your dots!

**Comment by JaKooLit** [comment]
sorry bro but no plans as I dont use nvidia optimus.. Im using the supergfxctl

why dont you try this instead?

https://github.com/bayasdev/envycontrol

There is alot of youtube videos out there

**Comment by TsugikuniVi** [comment]
Thanks!

Can you add this to the install script for those with Hybrid GPUs?

(Please create video for Hybrid Hyprland users... I am in desperate need for hyprland with igpu)

**Comment by JaKooLit** [comment]
sorry no.. I dont want to add cause if I add means I have to support.. and I cant support if I dont have means to actually install and ran
