### ISSUE TITLE
[Bug]: scripts have 'required file not found error'

### ISSUE THREAD

**Issue by yontuh** [JaKooLit/Hyprland-Dots#266]
### Description

I've loved your script on fedora, and want to try Hyprland + Nixos. Thus, my system is fairly fresh install, other than some packages, plasma 5 upgraded to 6, a change of default shell (to fish) and the addition of  `programs.hyprland.enable = true;` to configuration.nix.

I followed the install, but after running ./copy.sh got
`_bash: ./copy.sh: cannot execute: required file not found_` (I don't think the underscores exist in Konsole)
NOTE: I ran the script in fish, then/and bash.

I googled the issue, and tried dos2unix, didn't fix anything.

After that I rm the directory, and tried again(bash first), same result.

I tried running it through gui, Dolphin/Right Click/Run In Konsole and got
 the screenshot error below.

#### If not Nixos Specific:
follow install instructions

#### If Nixos Specific:
try installing Nixos in a VM?(mine is not in a VM)

### Screenshots
![Screenshot_20240512_195435](https://github.com/JaKooLit/Hyprland-Dots/assets/140224943/4d430b00-7a1c-4057-8534-f8cf79a8887e)

### Environment

Fresh Nixos Plasma
Hyprland already installed

- Nixos
- uname -a: 
- Linux nixos 6.6.30 #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024 x86_64 GNU/Linux
- `hyprctl version`: HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
- On Hardware (Laptop)

**Comment by JaKooLit** [comment]
seems like you added more . at the end based from your screenshot

I do have nixos on my system and its the same dots I am using ;)

some of members of my discord also use nixos and I believe they ranned the copy.sh as well

just a small note

https://github.com/JaKooLit/Hyprland-Dots/wiki/Other_Distros#-will-this-work-on-nixos

**Comment by yontuh** [comment]
You're saying an extra space after? I checked, and they're no spaces in the command I'm inputting - could there be an extra space added somehow after I send it? (I've tried kitty and konsole). Note: if I do touch test.sh and run it, it runs fine.

**Comment by JaKooLit** [comment]
![swappy-20240513-123451](https://github.com/JaKooLit/Hyprland-Dots/assets/85185940/37fb5776-3c04-4ba2-83a2-4b5dd9de52f4)
I just booted on my nixos and seems fine

redownloaded the latest one

**Comment by yontuh** [comment]
Hmmmm. I'll do some trouble shooting tomorrow, are there any tests you could suggest? I don't script, but I think I can get by with some ai helping.

**Comment by JaKooLit** [comment]
after you cd into Hyprland dots

type ./co then press tab.

it should auto populate the copy.sh

then press enter

@JohnRTitor 

is the full time nixos user I know who uses this dots

**Comment by JohnRTitor** [comment]
Looks like a bash path issue. 
Add `services.envfs.enable = true;` to your configuration and reboot.

**Comment by JaKooLit** [comment]
> Looks like a bash path issue. 
> Add `services.envfs.enable = true;` to your configuration and reboot. 
> 
> @JaKooLit though, I will recommend changing the scripts 
> `#!/bin/bash` to `#!/usr/bin/env bash`. This will also work on every distro and better than /bin/bash. 
> 
> Should I make a PR? 

dont want to actually...

its security issue 😁

**Comment by JohnRTitor** [comment]
Ohhh... Not sure how it's a security issue :) but okay

**Comment by yontuh** [comment]
Should I wait for a patch?

**Comment by JaKooLit** [comment]
> Should I wait for a patch?

not gonna happen

just do what @JohnRTitor  said

to add the services

its what I did to my nixos systems

**Comment by yontuh** [comment]
Thanks! I close the Issue?

**Comment by JaKooLit** [comment]
you can or you can wait until you've done those

**Comment by yontuh** [comment]
Thank you, the script is running!
