### ISSUE TITLE
[Bug]: Can't see the DE

### ISSUE THREAD

**Issue by iEloyB** [JaKooLit/Hyprland-Dots#275]
### Description

I installed it in a Ubuntu 24.04 LTS, everything worked PERFECTLY, and i loved it but the moment I rebooted the system and logged again, i found out that Hyprland is not shown in my desktop environment

### Steps to Reproduce

1. Install Ubuntu 24.04 LTS
2. Install git
3. Install https://github.com/JaKooLit/Debian-Hyprland
4. Reboot (it works)
5. reboot again (can't see the desktop environment

### Expected Behavior

Select Htprland as desktop environment and login

### Actual Behavior

I dont even see the desktop environment list

e.g.,

- Linux Distro: Ubuntu
- Linux Version, output of `uname -a`: Linux ubuntu 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Hyprland Version, output of `hyprctl version`: HYPRLAND_INSTANCE_SIGNATURE not set! (is hyprland running?)
- Hyprland-Dots version: `ls ~/.config/hypr` i.e. v2.2.1
- Installation Environment: On The Main Hardware

**Comment by JaKooLit** [comment]
next time, kindly fill up all the information as requires when filing an issue

to go back to your query,

did you choose hyprland on your GDM? or login manager?

**Comment by JaKooLit** [comment]
> Stop gdm from starting and use sddm

gdm is fine....

its actually more stable than sddm 😁 for hyprland

**Comment by iEloyB** [comment]
> next time, kindly fill up all the information as requires when filing an issue
> 
> to go back to your query,
> 
> did you choose hyprland on your GDM? or login manager?

Yeah, i accidently uploaded the issue, but i filled up the information instantly

**Comment by iEloyB** [comment]
> did you choose hyprland on your GDM? or login manager?

I dont know, how can i know it?

**Comment by JaKooLit** [comment]
![swappy-20240515-012401](https://github.com/JaKooLit/Hyprland-Dots/assets/85185940/251911d0-5a98-4a44-ba0e-97d2d0fa4aaa)
This is from KSK royale's video

**Comment by iEloyB** [comment]
> ![swappy-20240515-012401](https://private-user-images.githubusercontent.com/85185940/330519157-251911d0-5a98-4a44-ba0e-97d2d0fa4aaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MDc4ODgsIm5iZiI6MTcxNTcwNzU4OCwicGF0aCI6Ii84NTE4NTk0MC8zMzA1MTkxNTctMjUxOTExZDAtNWE5OC00YTQ0LWJhMGUtOTdkMmQwZmE0YWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE3MjYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjVhMjgwOWYwMjJjNDQ4Yjc5MzVhMTFmYTYwZDM2ZTgxZjE0ODZhZDg5ZWQxNzNiYTJlMmU4Mjg3ZmZmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ys435AO82PaPnHOk9H4eOd-R1JBg2dI5ntjTrwEJas) This is from KSK royale's video

Yeah that's the thing i was trying to explain that was not showing, but i reinstalled a new ubuntu in my PC and installed everything again with SDDM and it works perfectly, nice job btw, im in LOVE with this!
