### ISSUE TITLE
Settings 

### ISSUE THREAD

**Issue by DrunkenAlcoholic** [JaKooLit/Hyprland-Dots#29]
I am getting an waybar error for line 45 in Settings.conf

the message says `"group.groupbar.col.active. No such field" hyprland may not work correctly.`

//Edit
removed reference to waybar, has nothing to do with waybar

I am using Arch and I had originally manually installed hyprland, then used your Arch install script to update it with your configs

**Comment by JaKooLit** [comment]
install hyprland-git . The hyprland on arch repo is really old

yay or paru -S hyprland-git

**Comment by DrunkenAlcoholic** [comment]
yeah updating hyprland to the git version fixed the issue

thanks mate
