### ISSUE TITLE
Rofi Broken After Updating Dots

### ISSUE THREAD

**Issue by arghunter** [JaKooLit/Hyprland-Dots#30]
I updated my dots today on ubuntu. 
This is what happens whenever I try to open rofi
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/91099806/d203cd8f-f383-4a63-878a-c4ef9c505677)

Here is the file in question
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/91099806/da5e894a-a1c1-4bb9-9977-4d53086c0098)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ
