### ISSUE TITLE
GTK Settings not installed?

### ISSUE THREAD

**Issue by moxislut** [JaKooLit/Hyprland-Dots#308]
I had to reinstall Dots again because I was running into issues with my storage, however upon reinstalling I am missing everything that is needed for GTK Settings. Anyway I can reinstall them?

**Comment by JaKooLit** [comment]
I dont fully understand what you mean GTK Settings

**Comment by SherLock707** [comment]
I think he means nwg-look

**Comment by JaKooLit** [comment]
> I had to reinstall Dots again because I was running into issues with my storage, however upon reinstalling I am missing everything that is needed for GTK Settings. Anyway I can reinstall them?

if you are talking about nwg-look, yes you can reinstall no issues.
