### ISSUE TITLE
Some Keybindings are not working on my system - Specifically the "UserKeybindings"

### ISSUE THREAD

**Issue by Rodhor** [JaKooLit/Hyprland-Dots#317]
### Description

The UserKeybinding conf file does not seem to be loaded correctly. I cannot make the keybindings work proberly.

### Steps to Reproduce

I simply installed everything and could not get the keybindings to work. The Regular Keybindings work without a hitch. 

### Expected Behavior

For the keybindings like "MainMod + a" to work.

### Actual Behavior

Nothing.

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

Ubuntu 24.04

e.g.,

- Linux Distro: [e.g., ArchLinux, Debian, Fedora 39, OpenSuse]
- Linux Version, output of `uname -a`:
- Hyprland Version, output of `hyprctl version`:
- Hyprland-Dots version: `ls ~/.config/hypr` i.e. v2.2.1
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine]
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by Rodhor** [comment]
Super Enter works, Super D does not. With Super A I can open apps when the switchwindow opens.
I am on Hardware. 
The ags -t overview returns true and opens the windowswitcher.

**Comment by JaKooLit** [comment]
cd Ubuntu-Hyprland
./install-scripts/rofi-wayland.sh

this will reinstall rofi-wayland


very important NOT to cd in install-scripts directory


need to execute outside install-scripts directory

https://github.com/JaKooLit/Debian-Hyprland/tree/Ubuntu-24.04-LTS?tab=readme-ov-file#-proper-way-to-re-installing-a-particular-script-from-install-scripts-folder

**Comment by Rodhor** [comment]
Perfect, that worked. Thanks!
Great Configuration btw. really nice work!
