### ISSUE TITLE
[Bug]: Unkown Option when starting kitty

### ISSUE THREAD

**Issue by Prixix** [JaKooLit/Hyprland-Dots#318]
### Description
When starting kitty, the first thing that is going to happen is to output:
`unknown option: --zsh`

### Steps to Reproduce

1. Fresh Debian trixie install
2. Open kitty

### Expected Behavior

No error message

### Actual Behavior

Getting error message

### Environment

Debian 12.5

`Linux paulpc 6.7.12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.12-1 (2024-04-24) x86_64 GNU/Linux`

```
Hyprland, built from branch  at commit fe7b748eb668136dd0558b7c8279bfcd7ab4d759  (props: bump version to 0.39.1).
Date: Tue Apr 16 17:01:03 2024
Tag: v0.39.1, commits: 4460
```

Hyprland-Dots: v2.2.12

### Additional Information

Fixed by installing the git version of fzf by
`git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf`
`~/.fzf/install`

Just searched it up online. Apparently Debian repos are not up to date (https://github.com/junegunn/fzf/issues/2996#issuecomment-1695580144)

**Comment by JaKooLit** [comment]
cool thanks alot... I will adjust the install script for fuzzy finder...

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/commit/df4ff30d4a959171c21c223875dac9a123c30204

https://github.com/JaKooLit/Debian-Hyprland/commit/a0f05de29dec20ba135d31e15583590793735887
