### ISSUE TITLE
Lock Feature not working 

### ISSUE THREAD

**Issue by digvijayizing** [JaKooLit/Hyprland-Dots#319]
### Description -> Lock Feature not working on my ASUS Vivobook S15 OLED 

[Provide a clear and concise description of the bug.]-> Lock feature doesn't work more than once and when Locked if laptop gets folded and when unfolded the system automatically gets unlocked without asking for password

### Steps to Reproduce

1. Lock the system using the shortcut Ctrl + alt + L or by using the power icon 
2. The system for the first time will get locked and when unlocked repeat step 1 
3. Now No Lock action will take place 

### Expected Behavior
To be locked everytime when pressing Ctrl + alt +L or power icon 
[What did you expect to happen?]

### Actual Behavior
System doesnt get locked
[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

e.g.,

- Linux Distro: **Fedora 40** 
- Linux Version, output of `uname -a`: **Linux fedora 6.8.10-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC**
- Hyprland Version, output of `hyprctl version`: **0.40.0**
- Hyprland-Dots version: `ls ~/.config/hypr` i.e. v2.2.1 : **v2.2.12**
- Installation Environment: [e.g., On The Main Hardware, On A Virtual Machine] : Dual Booted Main Hardware
- Other info: [e.g., Display Resolution, Resolution, etc]

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by JaKooLit** [comment]
https://github.com/hyprwm/hyprlock/issues/329

https://github.com/hyprwm/hyprlock/issues?q=is%3Aissue+is%3Aclosedunlock+

**Comment by digvijayizing** [comment]
So will it fix the bug only or clean install a new hyprland with everything will be plain and had to be like customised again ?

**Comment by JaKooLit** [comment]
just install the git version of hyprland or you can wait for next hyprland version release

if you install hyprland-git, you wont need to costumize again


that will just upgrade your Hyprland package to git version instead of latest released version (0.40.0)

**Comment by digvijayizing** [comment]
Didn't worked
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/93901013/139767c6-4111-4f1b-b8e9-5a6d76d3bdea)

**Comment by JaKooLit** [comment]
sudo dnf autoremove hyprland && sudo dnf install hyprland-git

**Comment by digvijayizing** [comment]
Thanks Jay it worked !
