### ISSUE TITLE
[Bug]: RofiBeats.sh, local music:  not passing the chosen song to mpv

### ISSUE THREAD

**Issue by dazWiLLiE** [JaKooLit/Hyprland-Dots#334]
In the RofiBeats.sh script, your have the following code for playing local music:
`mpv --loop-playlist --vid=no "$mDIR"`
`mpv --playlist-start="$file" --loop-playlist --vid=no "$mDIR"`

The chosen song is not included.

Fixed with adding `/$choice`:

`mpv --loop-playlist --vid=no "$mDIR/$choice"`
`mpv --playlist-start="$file" --loop-playlist --vid=no "$mDIR/$choice"`

**Comment by JaKooLit** [comment]
Thanks alot

https://github.com/JaKooLit/Hyprland-Dots/commit/24ef1df9c20b74dff325cf9050d4fa18e6da6909

https://github.com/JaKooLit/Hyprland-Dots/commit/2c6b7c2e399e62ff43f6eaeb24ccfc87d00a2f08



https://github.com/JaKooLit/Hyprland-Dots/wiki/Changelogs#v2214-development
