### ISSUE TITLE
Hidpi and two screen problem

### ISSUE THREAD

**Issue by skyworldp** [JaKooLit/Hyprland-Dots#340]
I find Hidpi not work.I trid hyperconfig monitor  but the hyperctl command not found  I cant know my screen data.Also my second screen is rotated but it showed unproperly. Is there someway to re add the hyperctl command?

**Comment by JaKooLit** [comment]
its hyprctl not hyperctl


https://wiki.hyprland.org/Configuring/Using-hyprctl/


and anything hyprland bug related, kindly report to hyprland development page

https://github.com/hyprwm/Hyprland


unless of course its a configs issue then you can report here
