### ISSUE TITLE
[Bug]: Dialog boxes when first opened, open in workspace 0 regardless

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Hyprland-Dots#342]
### Description

Example, I use Proxmox.  To open the console I have to download a .VV file.  When I first start Hyrpland that save file diaglog box opens in Workspace 1   No matter what Workspace I was in   (Typicallyt WS2 )   

### Expected Behavior

 Open in the workspace I am currently in

 Turns out this "feature" was enabled but until recently wasn't showing up 

 To change the behavior you have to use the initial_workspace_tracking option in hyprland.conf 
I set mine to 0 to disable it under the 'misc',  category but don't believe that matters 
 misc {
                initial_workspace_tracking = 0

![image](https://github.com/JaKooLit/Hyprland-Dots/assets/129223418/64f2ef90-f792-4ef6-aa93-9f6c243baf96)

 FYI: I got this from hyprland discord   They say since 0.39 but never had it happen until now    Maybe changed to enabled by default? 

![image](https://github.com/JaKooLit/Hyprland-Dots/assets/129223418/b5eedc37-b7f8-4d74-a136-fe5aee24043f)

```


```

or you can also run `inxi -CGIsSMnr >diag.txt` and attach diag.txt

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/0d77d8a0b2a9d883927836525b76e02503e19dcd

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/releases/tag/v2.3
