### ISSUE TITLE
Unable to connect to a WiFi 

### ISSUE THREAD

**Issue by Muizzyranking** [JaKooLit/Hyprland-Dots#345]
I am using fedora KDE and I just installed hyprland with the config script.
I haven't changed the config (except for kitty), and I am unable to connect to a WiFi. It shows a pop up to connect to WiFi, I enter the password and it shows me that I have been disconnected.

**Comment by JaKooLit** [comment]
can you show screenshot?

**Comment by Muizzyranking** [comment]
I already deleted hyprland. I will try it again later, thank you for replying.
