### ISSUE TITLE
[Bug]: Hyprland build 0.41.1+  `new_is_master` not supported changed to: `new_status=master`

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Hyprland-Dots#346]
### Description
Jun 16,2024 build of hyprland changed ```new_is_master``` to ```new_status=master```

https://github.com/hyprwm/Hyprland/pull/6479

```
 master {
-  new_is_master=1
+  new_status=master
   new_on_top=1
   mfact = 0.5
 }
```

**Comment by JaKooLit** [comment]
thanks lot bro

https://github.com/JaKooLit/Hyprland-Dots/commit/f0c450219a246e22a2aba4c909e64b5eec826795

I will keep this open for those who are using the -git version

**Comment by RandomAct5** [comment]
Thank-you. I just updated hyprland (on Arch btw) and got this error:

> Config error in file ~/.config/hypr/hyprland.conf at line 108: config option <master:new_is_master> does not exist.

Anyone here by search, update as per @dwilliam62 post.
`new_status=master`

 Not sure if it fits here but sharing anyway.

**Comment by SSYH** [comment]
Install today (20241016); still had to do this manually :(

**Comment by JaKooLit** [comment]
> Install today (20241016); still had to do this manually :(

whats your distro?

**Comment by dwilliam62** [comment]
> Install today (20241016); still had to do this manually :(

That usually indicates the version of hyprland being older than 0.42 I believe is when that changed, or late 0.41.
