### ISSUE TITLE
[Feature Request]: Support to search and swtich to specified application in Overview

### ISSUE THREAD

**Issue by tonyho** [JaKooLit/Hyprland-Dots#348]
### Description

It will be convieient to search and switch to opened application and its workspace using keyboard. I think if this can be added into the Overview function(Win+A). 

### Use Case

To quick switch to search and opened application

### Proposed Solution

This repo has [Easy windows Manager ](https://github.com/end-4/dots-hyprland/tree/main)function, it seems like the function this issue prepose

### Alternatives

No

**Comment by JaKooLit** [comment]
I dont think end-4 has a search function for opened apps... you can use tab to switch to open apps after pressing super A

**Comment by tonyho** [comment]
> I dont think end-4 has a search function for opened apps... you can use tab to switch to open apps after pressing super A↳

As the hyprctl clients can list all opened apps, any tips to fast archive this function with yad combining with short key?

**Comment by tonyho** [comment]
After checked the manpage of rofi, I found it can be archive by using:
```
rofi -show window
```

This would launch rofi in window mode, and type + search + switch is ready.

**Comment by JaKooLit** [comment]
super D 

ctrl tab

choose windows
