### ISSUE TITLE
[Bug]: WLR_NO_HARDWARE_CURSORS is deprecated

### ISSUE THREAD

**Issue by deaver812** [JaKooLit/Hyprland-Dots#351]
According to the [hyprland wiki](https://wiki.hyprland.org/Nvidia/#environment-variables) WLR_NO_HARDWARE_CURSORS is deprecated and should no longer be used. it is reccomended to instead use:
cursor {
    no_hardware_cursors = true
}
I have noticed that your config files still include the former.

**Comment by JaKooLit** [comment]
Thanks alot. Much appreciated. 

Will probably issue one release for hyprland >v0.41

https://github.com/JaKooLit/Hyprland-Dots/commit/1d1101d5d96db905b35d160a5c4199bd26887da9

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/releases/tag/v2.3
