### ISSUE TITLE
[Bug]: Hyprland dots breaks kde ui.

### ISSUE THREAD

**Issue by DmitryHudrich** [JaKooLit/Hyprland-Dots#360]
### Description

I'm not sure if this is a bug, but this dots breaks the UI kde on arch, if you install it where after installing hyprland. This dots breaks all kde themes and colors. This is not fixed in any way by the settings of the environment itself. 

The only solution is to delete the lines from the file `UserConfigs/Startup_Apps.conf`
```
# Polkit (Polkit Gnome / KDE)
# exec-once = $scriptsDir/Polkit.sh
```
But this breaks rofi colors in hyprland...

### Steps to Reproduce

1. Install kde plasma 6 to arch linux
2. Login to plasma

### Expected Behavior

good ui

### Actual Behavior

bad ui

### Screenshots

![photo_2024-07-01_21-25-40(1)](https://github.com/JaKooLit/Hyprland-Dots/assets/130711005/f3395f92-ce30-4a8c-a1a7-720ce27a871c)

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: zaza-pc Kernel: 6.9.7-arch1-1 arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.41.2 Distro: Arch Linux
Machine:
  Type: Desktop Mobo: Gigabyte model: P67X-UD3-B3 serial: <superuser required>
    BIOS: Award v: F2 date: 03/25/2011
CPU:
  Info: quad core model: Intel Core i5-2550K bits: 64 type: MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 2777 min/max: 1600/3800 cores: 1: 3494 2: 1880 3: 3493
    4: 2241
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 555.58
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.0
    compositor: Hyprland v: 0.41.2 driver: X: loaded: nvidia
    unloaded: modesetting gpu: nvidia resolution: 1920x1080
  API: EGL v: 1.5 drivers: nvidia,swrast,zink
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 555.58
    renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
  API: Vulkan v: 1.3.279 drivers: nvidia surfaces: xcb,xlib,wayland
Network:
  Device-1: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: enp8s0 state: up speed: 1000 Mbps duplex: full mac: 50:e5:49:31:d8:1f
  Device-2: TP-Link TL-WN821N v5/v6 [RTL8192EU] driver: rtl8xxxu type: USB
  IF: wlp0s26u1u3 state: down mac: 5a:a8:f1:b1:ef:1b
Sensors:
  System Temperatures: cpu: 42.0 C mobo: N/A
  Fan Speeds (rpm): N/A
Repos:
  Active pacman repo servers in: /etc/pacman.d/mirrorlist
    1: https://mirror.osbeck.com/archlinux/$repo/os/$arch
    2: https://de.arch.mirror.kescher.at/$repo/os/$arch
    3: https://mirror.f4st.host/archlinux/$repo/os/$arch
    4: https://mirror.sunred.org/archlinux/$repo/os/$arch
    5: https://at.arch.mirror.kescher.at/$repo/os/$arch
    6: https://mirror.pseudoform.org/$repo/os/$arch
    7: https://mirror.theo546.fr/archlinux/$repo/os/$arch
    8: https://london.mirror.pkgbuild.com/$repo/os/$arch
    9: https://mirror.ubrco.de/archlinux/$repo/os/$arch
    10: https://mirror.moson.org/arch/$repo/os/$arch
    11: https://arch.phinau.de/$repo/os/$arch
    12: https://archlinux.thaller.ws/$repo/os/$arch
    13: https://md.mirrors.hacktegic.com/archlinux/$repo/os/$arch
    14: https://mirror.telepoint.bg/archlinux/$repo/os/$arch
    15: https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
    16: https://archlinux.za.mirror.allworldit.com/archlinux/$repo/os/$arch
    17: https://mirror.lty.me/archlinux/$repo/os/$arch
    18: https://mirror.ufscar.br/archlinux/$repo/os/$arch
    19: https://arch.mirror.constant.com/$repo/os/$arch
    20: https://archmirror.it/repos/$repo/os/$arch
Info:
  Memory: total: 12 GiB note: est. available: 9.7 GiB used: 4.09 GiB (42.2%)
  Processes: 232 Uptime: 4h 12m Shell: Zsh inxi: 3.3.35

```

**Comment by DmitryHudrich** [comment]
i'm sorry. my solution isn't work

**Comment by JaKooLit** [comment]
This is from my discord group:



This is for those who have installed hyprland alongside kde/plasma

by default QT apps theming are done by kvantum-manager through qt5ct / qt6ct 

if you want to use the themes you have set on your plasma, you need to edit the ENV-Variables

SUPER E - Choose ENV-Variables

edit these two lines

env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct

edit to look like this
env = QT_QPA_PLATFORMTHEME,kde
#env = QT_QPA_PLATFORMTHEME,qt6ct

you may also try to edit this

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

to look like this

env = XDG_CURRENT_DESKTOP,kde
env = XDG_SESSION_DESKTOP,kde


possibly add:
env = QT_STYLE_OVERRIDE,Breeze 

note:
Breeze is your theme

Make sure to 
Please take note that these are information I have gathered from reddit.

I have not tried since I only have hyprland on my system




Option 2, Use / launch kvantum-manager

**Comment by DmitryHudrich** [comment]
thanks!
