### ISSUE TITLE
Unable to paste from clipboard into terminal

### ISSUE THREAD

**Issue by lushmana** [JaKooLit/Hyprland-Dots#362]
### Description

I have a clean install of fedora workstation, then I used your fedora-hyprland scripts to install hyprland.
SUPER + H failed to work I had to install **yad**

Anyway I determined there is no key binding for wl-paste, so I added CTRL V binding but still no pasting into terminal.

I have removed the key binding as that killed of pasting into graphical applications, I'm fairly new to this environment so please ignore my ignorance if this is a trivial question.

Sorry to waste your time I see that CTRL + SHIFT+ V is the correct way to paste into a terminal.

Amazing what a little bit of googling can achieve!

[diag.txt](https://github.com/user-attachments/files/16103555/diag.txt)

**Comment by JaKooLit** [comment]
pasting on tty is ctrl shift v

copying is ctrl shift c
