### ISSUE TITLE
[Bug]: Warbar weather doesn't work with custom locations i.e. just says a place in New York

### ISSUE THREAD

**Issue by Mysticpasta1** [JaKooLit/Hyprland-Dots#363]
### Description

[Provide a clear and concise description of the bug.]
Warbar weather doesn't work with custom locations i.e. just says a place in New York

### Steps to Reproduce

Install hyprland dots, change to laptop v3

### Expected Behavior

changing name and weather to current location set in the system

### Actual Behavior

Random city in New York

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment
```
hyprland/cachyOS

```

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/TIPS#%EF%B8%8F-weather-app-related-for-waybar-and-hyprlock
