### ISSUE TITLE
[Docs]: Change keys order for switch keyboard layout

### ISSUE THREAD

**Issue by AstralCookie** [JaKooLit/Hyprland-Dots#379]
### Description

Change the keys order for `Switch Keyboard Layout` in the [Keybinds](https://github.com/JaKooLit/Hyprland-Dots/wiki/Keybinds) page

I just spent 1 hour trying to understand why the 'Switch Keyboard Layout' keybind wasn't working to finally see the bindn in the UserKeybinds.conf

`bindn = ALT_L, SHIFT_L, exec, $scriptsDir/SwitchKeyboardLayout.sh # Changing the keyboard layout`

And understand that it's not `Shift + ALT_L` but `ALT_L+Shift`. Otherwise if you try the first combination it'll do nothing

### Current Documentation

https://github.com/JaKooLit/Hyprland-Dots/wiki/Keybinds

### Proposed Documentation

Reverse the order to match what the actual keybind is `ALT_L + SHIFT`

**Comment by JaKooLit** [comment]
Thanks bro. Keybinds updated
