### ISSUE TITLE
[Bug]: Some shortcuts do not work

### ISSUE THREAD

**Issue by mesflit** [JaKooLit/Hyprland-Dots#382]
For example, while $SUPER + Q works, shortcuts that specify the file path, such as $scriptDir + ..., do not work.

NixOS Unstable

**Comment by JaKooLit** [comment]
need some more info as I dont have issue on my NixOS

**Comment by mesflit** [comment]
I reviewed the config file and downloaded all the necessary programs.
For example Super + Q works, it's a simple command. It works in Super + D for example.
However, shortcuts that specify the file path, such as $scriptDir/Keyhints.sh, do not work, but when I run Keyhints.sh with bash, that is, when I run it as an sh file, it works.

**Comment by JaKooLit** [comment]
pls share your nixos configs

**Comment by mesflit** [comment]
> pls share your nixos configs

I think there is no need for this, things I do is add searxng. was to add a user and add the necessary programs to the configuration

**Comment by JaKooLit** [comment]
well then I couldnt be of much help

in any case I placed here a pointers

https://github.com/JaKooLit/Hyprland-Dots/wiki/Other_Distros#-will-this-work-on-nixos
