### ISSUE TITLE
[Feature Request]: Reference $EDITOR environment variable in QuickEdit.sh

### ISSUE THREAD

**Issue by ningen** [JaKooLit/Hyprland-Dots#385]
I am Japanese and am using the translation function to write this issue.

### Description

Reference $EDITOR environment variable in QuickEdit.sh

### Use Case

I used this repository to build a hyperland environment.
When I tried to change the settings, nano started.
I wanted to use neovim, so I set the $EDITOR variable because I knew that in linux, the editor you want to use is set to $EDITOR by default.
I was hoping that I would be able to use neovim now, but I was surprised that nano still started.
By making this change, new users can use their favorite editor without hesitation.

### Proposed Solution

As the title suggests, if $EDITOR is set, that editor will be used.
If not set, use nano.

### Alternatives

I modified QuickEdit.sh myself.

### Additional Information

[Add any other information about the feature request here. For example, you might include links to similar features in other projects, or screenshots or diagrams to help explain your idea.]

**Comment by ningen** [comment]
I can prepare a merge request.
We will probably create a merge request within 2-3 days.
This is my first OSS contribution, so there may be some mistakes.

**Comment by ningen** [comment]
I created a pull request.
Please check.

https://github.com/JaKooLit/Hyprland-Dots/pull/386

**Comment by JaKooLit** [comment]
merged into development for further testing.

thanks..

Made a comment on PR that there is no need to create an issue for creating PR.
