### ISSUE TITLE
[BUG] SUPER B only Hides waybar but not unhide

### ISSUE THREAD

**Issue by JaKooLit** [JaKooLit/Hyprland-Dots#391]
As per Title

keybind SUPER B hides waybar

however, it does not unhide

some work around
SUPER ALT R

**Comment by JaKooLit** [comment]
https://github.com/Alexays/Waybar/issues/3467


well guess we have to wait for the next release or install/build from upstream or -git version

**Comment by Amag1n3** [comment]
my 2 cents on fixing this "issue"
I changed my "Default Keybinds" file to:
bind = $mainMod, B, exec, killall waybar || waybar 

This works, but I recon you'd have to reload with CTRL+ALT+R to get the color themeing

**Comment by JaKooLit** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/commit/0306af03fcb6de6aee1e288f42b0bf1b223513bd

Arch linux updated their official repo

confirmed
extra/waybar 0.10.4-2 fixed this issue
