### ISSUE TITLE
[BUG] Screen sharing error on meet platforms

### ISSUE THREAD

**Issue by EstevenSanz** [JaKooLit/Hyprland-Dots#392]
## Screen sharing error on meet platforms

When sharing screen in a meet, it gives me the option to choose screen, option that is shown two or three times, I select the screen to share and it cannot be displayed.

### Steps to Reproduce

1.I press the share button.
2. Select the option you want to use (full screen, one window or one tab).
3. And at the end my screen is not displayed in the meet.

### Screenshots
![swappy-20240804-213858](https://github.com/user-attachments/assets/59f8ae34-df0d-44fd-81af-d8a4ba4216f5)
![swappy-20240804-214158](https://github.com/user-attachments/assets/52b77608-7704-4af9-991c-8959c277e69d)
![swappy-20240804-214231](https://github.com/user-attachments/assets/f43384e1-6f44-4ec6-81c5-e89aa892d33b)
![swappy-20240804-214304](https://github.com/user-attachments/assets/335c21a6-b203-46de-be21-bdfdbdd350c7)
![swappy-20240804-214359](https://github.com/user-attachments/assets/d5a06e0a-435a-4c2e-8093-3ee08d995ba1)
![swappy-20240804-214551](https://github.com/user-attachments/assets/13d3b6fd-4798-4e43-8713-48316d9bb5a4)
![swappy-20240804-215241](https://github.com/user-attachments/assets/580ff2b8-3e3b-4f7d-9cf6-8de553578584)

```
CPU: quad core AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (-MT MCP-)
speed/min/max: 1635/1400/2100 MHz Kernel: 6.9.12-200.fc40.x86_64 x86_64
Up: 27m Mem: 2.38/5.69 GiB (41.8%) Storage: 238.47 GiB (23.2% used) Procs: 323
Shell: Zsh inxi: 3.3.34
```
### Meets used.
(Jitsimeet, google meet, gather, microsoft teams, zoom)

**Comment by JaKooLit** [comment]
https://wiki.hyprland.org/Useful-Utilities/Screen-Sharing/#xwayland

**Comment by EstevenSanz** [comment]
Thank you very much!!!
