### ISSUE TITLE
[Bug]: Launch wrong lib in PortalHyprland.sh?

### ISSUE THREAD

**Issue by vunhatchuong** [JaKooLit/Hyprland-Dots#393]
In [PortalHyprland.sh](https://github.com/JaKooLit/Hyprland-Dots/blob/d7399e0d96cc68f8bc5b3203f74699ce50ac9944/config/hypr/scripts/PortalHyprland.sh#L14), I think it's supposed to be `/usr/lib/xdg-desktop-portal &`

```diff
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal-hyprland &
/usr/libexec/xdg-desktop-portal-hyprland &
sleep 2
--/usr/lib/xdg-desktop-portal-hyprland &
++/usr/lib/xdg-desktop-portal &
/usr/libexec/xdg-desktop-portal &
```

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/41c4923fe79b1462a54881705a580b730405a370

youre right

thanks


ive pushed to main
