### ISSUE TITLE
[Bug]: Hyprland 0.42 new aquamarine backend nuked waybar

### ISSUE THREAD

**Issue by THMprod** [JaKooLit/Hyprland-Dots#396]
### Description

Hyprland 0.42 just come and the big feature it's the replacement of wlroot for the home hyprland backend aquamarine.
And after the update, waybar is now a big red bar who show issue

### Steps to Reproduce

Update Hyprland on Fedora

### Actual Behavior

Waybar no longer work and it's just a red warning bar

### Environment

Fedora KDE with the hyprland script to install it

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Fedora-Hyprland/commit/9fbe87e23a9a0c96fd1d78e4926b45102c1a39ba
