### ISSUE TITLE
[Bug]: Wallpaper Select - Random not updating wallust colors

### ISSUE THREAD

**Issue by JaKooLit** [JaKooLit/Hyprland-Dots#397]
### Description

As stated above. When choosing wallpaper using Keybind (SUPER W), after choosing random, it seems that it is not updating the colors on rofi, waybar etc..

Wallpaper is changing though

**Comment by nirmaleeswar30** [comment]
it seems that when installing the script the build for wallust-git fails everytime and this has to do something with rust check the latest comments here https://aur.archlinux.org/packages/wallust-git

**Comment by StichyHD** [comment]
Just download a his fix he did earlier today i reported it in his discord 
https://github.com/JaKooLit/Hyprland-Dots/commit/9b3751df6bad9a2548c6a430679fd414b737e698

**Comment by StichyHD** [comment]
https://github.com/JaKooLit/Hyprland-Dots/blob/9b3751df6bad9a2548c6a430679fd414b737e698/config/wallust/wallust.toml 

he already did a quick fix today i reported the other night

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/d08a0b34245866e06e5c83e5c6f1d0e898e93984
