### ISSUE TITLE
[Bug]: doesnt work password entry window

### ISSUE THREAD

**Issue by MickeyHatake** [JaKooLit/Hyprland-Dots#400]
hello, im use Oracle VM VirtualBox, 
![image](https://github.com/user-attachments/assets/aba79081-d738-4266-9acd-f7b88885fbef)
When im input password, a black screen appears for a few seconds, returning to the password entry window.
how to fix it?

**Comment by MickeyHatake** [comment]
im use archinstall, when need chose "Profile" im select "Minimal", later im use u script

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-it-goes-back-to-log-in-manager-after-install

**Comment by MickeyHatake** [comment]
solved
