### ISSUE TITLE
UserSettings.conf at line 166: config option <render:explicit sync> does not exist.

### ISSUE THREAD

**Issue by txl263** [JaKooLit/Hyprland-Dots#404]
Config error in file /home/dev/ config/hypr/UserConfigs/UserSettings. conf at line 166: config option <render explicit sync> does not exist.
![image](https://github.com/user-attachments/assets/1de6bd93-564d-479c-8e18-30f336cf987b)

![iShot_2024-08-18_17 08 13](https://github.com/user-attachments/assets/2f8021cb-069b-4fe8-bdcf-1de1e0761439)

https://github.com/JaKooLit/Hyprland-Dots/blob/bcd9b72d4704f5be1c8957051df7745e05cb0ba5/config/hypr/UserConfigs/UserSettings.conf#L165

**Comment by JaKooLit** [comment]
whats your distro and Hyprland version? 

those are for Hyprland v0.42.0
