### ISSUE TITLE
[Bug]: Dropdown terminal appears in the taskbar module

### ISSUE THREAD

**Issue by asunekants** [JaKooLit/Hyprland-Dots#406]
### Description

The dropdown terminal appears in the taskbar module in waybar even when the drop down terminal is hidden; Clicking on it brings up the terminal which appears "out of bounds", messing up the visual geometry.

### Steps to Reproduce

1. Use a waybar layout that has the wlr/taskbar module active.
2. Launch the drop-down terminal once and escape it to hide it.
3. The hidden drop-down terminal appears in the taskbar as per the description.

### Expected Behavior

The drop-down terminal doesn't appear in the taskbar.

### Actual Behavior

As per the Description.

### Screenshots

didn't take screenshots before I fixed it on my local system, unfortunately.

### Environment

The issue happens because pypr spawns the drop-down window with the "kitty-dropterm" class instead of "kitty", which is correctly blocklisted.

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```


```

or you can also run `inxi -CGIsSMnr >diag.txt` and attach diag.txt

### Additional Information

The issue is very simple, no additional info needed.
[diag.txt](https://github.com/user-attachments/files/16666251/diag.txt)

**Comment by asunekants** [comment]
Logged PR https://github.com/JaKooLit/Hyprland-Dots/pull/407 to fix the config.

**Comment by JaKooLit** [comment]
thanks

merged on development branch
