### ISSUE TITLE
Weather script may be broken

### ISSUE THREAD

**Issue by Balssh** [JaKooLit/Hyprland-Dots#41]
Hi, I'm trying out your script and dotfiles and noticed that the wheater.py script is throwing out errors. I also tried to directly call the site wttr.in but google doesn't find it.
Is the site correct?

LE: the bash script doesn't work either.

**Comment by darkeddie** [comment]
1. Did you edit your city name into the script?
2. Does https://wttr.in/YOUR_CITY work in your browser?

**Comment by Balssh** [comment]
Yup, I added the city name. But I think the site was down, because I tried to access it and it didn't work. In the meantime it came online and the script works, will close this.
