### ISSUE TITLE
[Bug]: Fix laptop-lid action (to erase the last entry)

### ISSUE THREAD

**Issue by devax** [JaKooLit/Hyprland-Dots#412]
### Description

There seems to be an error in Laptops.conf which prevents the laptop monitor to be reset properly, when the feature is enabled.

In Laptops.conf, this line: 
`exec-once = echo "eDP-1, preferred, auto, 1" > $HOME/.config/hypr/UserConfigs/LaptopDisplay.conf`
shold be changed to this:
`exec-once = echo "monitor = eDP-1, preferred, auto, 1" > $HOME/.config/hypr/UserConfigs/LaptopDisplay.conf`

### Steps to Reproduce

1. Edit Laptops.conf: Enable the last section about laptop lids (the LaptopDisplay.conf option)
2. Close, then re-open laptop lid
3. Reboot

### Expected Behavior

No warning visible after login

### Actual Behavior

Warning visible: "Config error in file ~/.config/hypr/UserConfigs/LaptopDisplay.conf at line 2: Invalid config line"

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/08908174365672175e767c6fd5abe3f1a049e2be

Thanks lot..

**Comment by DR44ANK** [comment]
I don’t know, man, I just changed and uncommented the line
HandleLidSwitch=ignore in the logind.conf file located at:
/etc/systemd/logind.conf
And everything started working for me.
