### ISSUE TITLE
[Bug]: OBS aint working

### ISSUE THREAD

**Issue by ismayeelanver** [JaKooLit/Hyprland-Dots#414]
### Description

my obs aint showing the display capture option

### Expected Behavior

i expected to have my obs with display capture

### Actual Behavior

the display capture option is gone

### Screenshots
![Screenshot_26-Aug_11-42-40_20338](https://github.com/user-attachments/assets/b8cdb0d8-7bb0-4ca4-9d6e-869117752646)

**Comment by JaKooLit** [comment]
https://gist.github.com/brunoanc/2dea6ddf6974ba4e5d26c3139ffb7580

make sure you follow that

to force start xdg-desktop-portal-hyprland

edit StartUp Apps.conf

SUPER E Startuo Apps
