### ISSUE TITLE
[Bug]: ScreenShot error

### ISSUE THREAD

**Issue by zhang-yunqi** [JaKooLit/Hyprland-Dots#415]
Already moved the tmpfile but remove.
![image](https://github.com/user-attachments/assets/26d3a153-24a8-43c8-bb04-bf7ee15edd95)
![image](https://github.com/user-attachments/assets/00db07ae-8374-42bd-9871-2b0b2f2778e1)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/804c3cde6e988786a7f5205d47d37210f554ded3

Thanks bro

![Screenshot_28-Aug_18-07-48_14800](https://github.com/user-attachments/assets/e16a8fa5-106c-478e-9b2a-31c9ff2a56d5)
