### ISSUE TITLE
How do I get rid of the kanji and replace it with normal numbers

### ISSUE THREAD

**Issue by ieatbeansbruh** [JaKooLit/Hyprland-Dots#418]
Didn't find this in the documentation and I genuinely tried to figure it out myself

**Comment by JaKooLit** [comment]
https://youtu.be/jBPVAsLkmCM?si=T-7Kj7GMCI6p1CWS

about 4:00

should give an idea


and also, https://github.com/Alexays/Waybar/wiki

a good read
