### ISSUE TITLE
[Bug]: Unable to switch layouts

### ISSUE THREAD

**Issue by AlexBarsky** [JaKooLit/Hyprland-Dots#422]
### Description

Right after the installation I could not change the layout. Although I did get the notification about successfully changed layout and no errors were popping up.

### Output of SwitchKeyboardLayout.sh script
```
$ ~/.config/hypr/scripts/SwitchKeyboardLayout.sh
Starting script...
Current layout: ru
Reading keyboard layout settings from /home/barsky/.config/hypr/UserConfigs/UserSettings.conf...
Available layouts:  us ru
Number of layouts: 2
Current layout index: 1
Next layout:  us
Switching layout for asus-wireless-radio-control to  us...
invalid arg 2
...
Switching layout for at-translated-set-2-keyboard to  us...
invalid arg 2
Switched the layout for at-translated-set-2-keyboard.
Layout change notification sent.
```

### Explanation

As you can see in the output there are no critical errors, but there is some issue and that is ```invalid arg 2```. After a brief exploring in [Hyprland Docs](https://wiki.hyprland.org/Configuring/Using-hyprctl/#switchxkblayout) I discovered this:

> ```hyprctl switchxkblayout [DEVICE] [CMD]```
> 
> where CMD is either next for next, prev for previous, or ID for a specific one (in the above case, us: 0, pl: 1, de: 2). You can find the DEVICE using hyprctl devices command.
> 
> DEVICE can also be current or all, self-explanatory. Current is the main keyboard from devices.

But in the script there is this:
```hyprctl switchxkblayout "$name" "$new_layout"```

where $new_layout is symbols, like us, en, ru, etc.

### Solution

Just change ```hyprctl switchxkblayout "$name" "$new_layout"``` (64 line) to ```hyprctl switchxkblayout "$name" next``` or use layout index instead of 'next'.
I`m not sure that I didn`t somehow messed up the installation or post-installation stage, but that`s what I got out of the box and how I fixed it.

**Comment by JaKooLit** [comment]
Thanks for this.. Im not sure how this is actually cause you close in an instant ha ha

hyprctl switchxkblayout "$name" next

does this actually works?

Im sorry I am asking since I dont have multiple keyboard layout

however, I just tried adding another keyboard layout and notification is ok but not sure if it is working properly

**Comment by AlexBarsky** [comment]
> Thanks for this.. Im not sure how this is actually cause you close in an instant ha ha
> 
> hyprctl switchxkblayout "$name" next
> 
> does this actually works?
> 
> Im sorry I am asking since I dont have multiple keyboard layout
> 
> however, I just tried adding another keyboard layout and notification is ok but not sure if it is working properly

According do Hyprland Docs its working, and I`m currently using it. And notifications were working fine. That`s why I showed only the script output.

P. S. I closed the issue immediately because I  solved it, and was just trying to help some who could encounter with similar problem.
