### ISSUE TITLE
Removing outline

### ISSUE THREAD

**Issue by Leadoffspoon934** [JaKooLit/Hyprland-Dots#423]
Hi, 

Love the dots but which setting removes the outline glow from all the windows? I got rid of the rainbow border, but can't get rid of the overall outline.

**Comment by JaKooLit** [comment]
Hello.

you can edit Settings 
Super E - UserSettings

General - remove or adjust as you see fit.
there is also col.active_border

Super E - Animations and Decorations

decoration - you will also see shadow.
same as above - adjust as you see fit

https://wiki.hyprland.org/Configuring/Variables/
