### ISSUE TITLE
mirror screen

### ISSUE THREAD

**Issue by ANRY17** [JaKooLit/Hyprland-Dots#43]
Hello, I want to mirror my laptop screen to the projector with the code:

# Monitors
monitor=eDP-1,preferred,auto,1
monitor=HDMI-A-1,preferred,auto,1,mirror,eDP-1

After connecting, the wallpaper becomes black. I have previously used Hyprland v4, which used swaybg and did not encounter any bugs after mirroring the laptop screen.

this is my code for persistant wallpaper :

# wallpaper stuff
exec-once = swww query || swww init && swww img $HOME/Pictures/wallpapers/Girls-Sky-Blue.jpg

**Comment by JaKooLit** [comment]
I have tried just now...

and yes initially will get black screen (no wallpaper) but when I press super w,  to select wallpaper, wallpaper came back again...

so try..

if didnt work, try to remove the persistent wallpaper

**Comment by ANRY17** [comment]
"Thank you, the wallpaper has reappeared, but I have another issue regarding fonts. I installed Windows fonts that I placed in /home/mydirectory/.local/share/font, but it changes all the fonts after the laptop is restarted, such as in Waybar, Rofi, terminal, and notifications."

#It's an example

![Screenshot_2023-11-29-18-21-52_468](https://github.com/JaKooLit/Hyprland-Dots/assets/90314986/1c4f6573-1737-4041-bc6a-cfec94195c8b)

#This is the font

https://drive.google.com/drive/folders/18W3DndDQ4Kb4NLEgf1dWnL0PqeTpIq1D?usp=sharing

**Comment by JaKooLit** [comment]
I dont know... you may need to set the default font using nwg-look

**Comment by ANRY17** [comment]
Thank you for your support. I think everything is going well now. I will close the session
