### ISSUE TITLE
[Bug]: Clipboard Issue: Unable to Copy from Brave to VSCode in Wayland (Hyprland)

### ISSUE THREAD

**Issue by Linxford** [JaKooLit/Hyprland-Dots#430]
I'm encountering an issue with clipboard functionality when copying text from the Brave browser to VSCode in a Wayland environment (Hyprland). The clipboard works as expected when copying from VSCode to Brave, but not the other way around. Copying from Brave to other applications (e.g., terminal, text editors like Vim) works fine, and clipboard functionality is also fine in Firefox.

Steps to Reproduce:

Running Brave with native Wayland support (--enable-features=UseOzonePlatform --ozone-platform=wayland).
Running VSCode in XWayland (default) or with Wayland support (--enable-features=UseOzonePlatform --ozone-platform=wayland).
Copy text from Brave and attempt to paste it into VSCode using Ctrl + V or right-click → Paste.
Pasting does not work in VSCode.
Expected Behavior: Copied text from Brave should be pasteable in VSCode like it works with other applications (e.g., terminal, text editors, Firefox).

Actual Behavior: Pasting does not work in VSCode when copying from Brave.

Environment:

OS: Arch Linux
Compositor: Hyprland (Wayland)
Brave Version:  v128.0.6613.120
VSCode Version: v1.93.0
Clipboard Manager: cliphist is being used for clipboard management.
Wayland Protocols: wl-clipboard is installed.
Workarounds Attempted:

Using cliphist to manually select and paste from the clipboard history.
Running Brave in XWayland mode (--disable-features=UseOzonePlatform).
Running VSCode in native Wayland mode (--ozone-platform=wayland).
Switching to Firefox resolves the issue, but I prefer using Brave.
Additional Notes: This appears to be an issue with how Brave interacts with clipboard management in Wayland environments. The issue persists even when using clipboard managers like cliphist. Clipboard contents from Brave do not seem to be recognized by VSCode.

**Comment by JaKooLit** [comment]
This is just wayland-electron drama and honestly, I dont have a fix. But I will keep this open in case I can find answer or somebody will chime in later

**Comment by VitalyyBezuglyj** [comment]
@JaKooLit that was the perfect clarification =)

Found a solution [here](https://forum.vivaldi.net/topic/98633/arch-hyprland-can-t-paste-text-copied-from-electron-apps-such-as-vscode-or-discord-in-vivaldi/3)


So you need to find the .desktop entry for your application, mine (fedora) was located at `/usr/share/applications/code.desktop` and modify

`Exec=/usr/share/code/code/code %F`.

to
`Exec=/usr/share/code/code --enable-features=UseOzonePlatform --ozone-platform=wayland %F`.

Then run logiut-login


P.S. According to the source - this can work for more than just vscode

Translated with DeepL.com (free version)

**Comment by JaKooLit** [comment]
thanks for the info.. Pls try and if works, im gonna pin this issue and add to FAQ on the dots wiki

**Comment by JaKooLit** [comment]
can you try to see if its it clipboard manager?

after copy and wont paste

open clipboard manager

super alt V

then click and paste

**Comment by JaKooLit** [comment]
oh... well they are both electron based. So its al electron issue
