### ISSUE TITLE
Kali-Linux rofi shortcuts not working

### ISSUE THREAD

**Issue by vasusingh9717** [JaKooLit/Hyprland-Dots#431]
Hi, 

Just installed hyprland. Having issue with keys. Not working. What to do. I tried your key file some of them are working and some are not. 

### Description

I am using hyprland over Kali Linux. I've installed hyprland as you have shown in the YouTube video. I am trying to run commands with super key but only 3 commands are working even hint isn't working. The only command which is working is super + enter, super + T, super + f. these are the only three commands which are working. 

### Expected Behavior

I expected to run commands but I couldn't as I have already mentioned. Commands aren't working. Only three commands are working. I expected to work all these commands. 

### Actual Behavior

When I press super + E, super + A or any other command nothing is happening. No window is opening.

###screenshot
https://github.com/user-attachments/assets/6479d2c7-f853-409e-a358-f4a2ab126443
I've also attached the video. Just like that, if I press any command nothing happening or no window is opening.

show output of inxi

dual .core AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx (-MT MCP-) speed/min/max: 2516/1400/2600 MHz Kernel: 6.6.15-amd64 x86_64 Up: 30m
Mem: •1.15/5.73 GiB (20.0%) Storage: 1.03 TiB (2.0% used)
Procs: 204 Shell: Zsh
inxi:
3.3.36
```

**Comment by JaKooLit** [comment]
pls complete all the details needed on the template.

Kindly edit all completing all the details
https://github.com/JaKooLit/Hyprland-Dots/tree/main/.github/ISSUE_TEMPLATE

**Comment by vasusingh9717** [comment]
> pls complete all the details needed on the template. Either you edit this or close and create a report
> 
> 

I've updated info. Pls check

**Comment by JaKooLit** [comment]
I have just checked and yad package is not in Debian Trixie but instead its only available in SID...

anyway, you can try to install yad from the assets which I uploaded in Debian-Hyprland repo
https://github.com/JaKooLit/Debian-Hyprland/commit/1662f6a8106e185a2479931d7d79540863d864df

this yad package is downloaded from 
https://debian.pkgs.org/sid/debian-main-amd64/yad_0.40.0-1+b2_amd64.deb.html


as for your other concern,

it seems like rofi-wayland is not installed

cd Debian-Hyprland 
edit install-scripts/rofi-wayland.sh

nano install-scripts/rofi-wayland.sh
remove the clear at the end and save

execute install of rofi-wayland.sh
./install-scripts/rofi-wayland.sh

NOTE: DO NOT CD into install-scripts directory else script will fail


the reason why I asked to remove the clear is to see if there are errors....

**Comment by vasusingh9717** [comment]
> I have just checked and yad package is not in Debian Trixie but instead its only available in SID...
> 
> 
> 
> anyway, you can try to install yad from the assets which I uploaded in Debian-Hyprland repo
> 
> https://github.com/JaKooLit/Debian-Hyprland/commit/1662f6a8106e185a2479931d7d79540863d864df
> 
> 
> 
> this yad package is downloaded from 
> 
> https://debian.pkgs.org/sid/debian-main-amd64/yad_0.40.0-1+b2_amd64.deb.html
> 
> 
> 
> 
> 
> as for your other concern,
> 
> 
> 
> it seems like rofi-wayland is not installed
> 
> 
> 
> cd Debian-Hyprland 
> 
> edit install-scripts/rofi-wayland.sh
> 
> 
> 
> nano install-scripts/rofi-wayland.sh
> 
> remove the clear at the end and save
> 
> 
> 
> execute install of rofi-wayland.sh
> 
> ./install-scripts/rofi-wayland.sh
> 
> 
> 
> NOTE: DO NOT CD into install-scripts directory else script will fail
> 
> 
> 
> 
> 
> the reason why I asked to remove the clear is to see if there are errors....
> 
> 
> 
> 
> 
> additional NOTE: you must use Debian-Hyprland install script since Kali Linux is based on Debian
> 
> 

Okay. I'll try and update

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/issues/159

**Comment by vasusingh9717** [comment]
> https://github.com/JaKooLit/Debian-Hyprland/issues/159

Thanks mate! It's working🤩

**Comment by JaKooLit** [comment]
> > https://github.com/JaKooLit/Debian-Hyprland/issues/159
> 
> Thanks mate! It's working🤩


cool.. so what about the rofi-wayland?

**Comment by vasusingh9717** [comment]
> > > https://github.com/JaKooLit/Debian-Hyprland/issues/159
> > 
> > Thanks mate! It's working🤩
> 
> 
> cool.. so what about the rofi-wayland? 
> 

It is also working now
