### ISSUE TITLE
[Bug]: Keyboard layout glitches

### ISSUE THREAD

**Issue by VitalyyBezuglyj** [JaKooLit/Hyprland-Dots#433]
Faced with the fact that the change of keyboard layout periodically hangs

Regardless of the key combination, it works like clockwork, then it can take a few seconds to actually change the layout.

That is, the notification comes, the icon in bar changes, but the characters continue to come from the same layout as they were.

Considering that sometimes it has to be changed several times in a row, this is a big nuisance.

Can you tell me where to look?

P.S. I found [this method](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#switchable-keyboard-layouts)  in Hyperland documentation, but your repository uses a relatively long shell script, why is that? Just trying to figure it out

**Comment by JaKooLit** [comment]
somebody made a PR on it before. Basically, it will also include all external keyboard. With default hyprland wiki, it will only affect the "internal" keyboard and not the externally connected devices via bluetooth or wireless.. that atleast his explanation



Personally, I dont use other layout. If you have a better solution, then Ill be happy to correct by merging your PR (if you have) or if there are corrections needed

**Comment by VitalyyBezuglyj** [comment]
Okay got it) 
Thanks!

Then I'll close it for now.
