### ISSUE TITLE
[Bug]: Swaync waybar module not visible  

### ISSUE THREAD

**Issue by Yaaneva** [JaKooLit/Hyprland-Dots#435]
### Description

My pc recently broke and I got it repaired. Fortunately, my motherboard was ok. After logging into my system after a long time. Everything was fine (swaync module was visible too) but a lot of update had built up (I use arch). So, I updated and rebooted my system and after that the module was gone, I believe. I tried rewriting the custom/swaync but nothing works :( 

### Steps to Reproduce

No particular steps to reproduce.

### Expected Behavior

Normal as things should be.

### Actual Behavior

Only the swaync module was invisible. When I click on the blank space it works as it normally does though. It's not broken but it's just not visible.

### Screenshots

![Screenshot_14-Sep_02-03-03_6701](https://github.com/user-attachments/assets/00ec896b-e371-410d-8c44-6b650236c5ab)

### Additional Information

I also updated my dotfiles. I don't know if it's because of that...

**Comment by JaKooLit** [comment]
hmmmm.....

can you try

super alt R
super shift N
see if swaync is working

then choose another waybar layout

since you have made changes on swaync module, I suggest to bring that back

**Comment by dwilliam62** [comment]
I can verify it also.  The icon is missing but it still works fine.  I tried your suggestions and they didn't resolve it   Happens on NIXOS, and Arch for sure   Attached screenshot 

![Screenshot_14-Sep_04-28-47_43](https://github.com/user-attachments/assets/7ea8876b-ff92-462c-9a52-b14d727045ec)

**Comment by JaKooLit** [comment]
https://github.com/Alexays/Waybar/releases/tag/0.11.0

ha ha... well must be due to new waybar released...

will have to check out later

just went out for my daily walk

anyway, can you guys try this

edit ~/.config/waybar/modules

line 726 

under custom/swaync
       "format": "{icon} {}",


remove the {}

final 

        "format": "{icon}",

save SUPER ALT R


if didnt fix, I will check later

**Comment by dwilliam62** [comment]
Yup that resolved it.

 Easy fix.  :)

Don

**Comment by JaKooLit** [comment]
ok so I tried it...

first on Arch, updated and yep it is gone.....

the above quick fix somehow fixed it.....

BUT, when I tried adding it again, swaync icon still there

just to be clear adding {} it just means number of notification

**Comment by Yaaneva** [comment]
> ok so I tried it...
> 
> first on Arch, updated and yep it is gone.....
> 
> the above quick fix somehow fixed it.....
> 
> BUT, when I tried adding it again, swaync icon still there
> 
> just to be clear adding {} it just means number of notification

Yes, removing "{}" fixes it but adding "{}" makes it disappear again for me unfortunately.
This means I just won't get the notification number huh? That's unfortunate.

**Comment by JaKooLit** [comment]
after you remove {} just reboot first

after first reboot try to bring it back again

two distros ive tried.

**Comment by JaKooLit** [comment]
Ok heres a very odd thing I discovered

I have upgrade to waybar-git for version 0.11

if I put the {} on the right, icon disappear.

if I put the {} on the left, icon stays 

what an odd bug lmao

**Comment by Yaaneva** [comment]
> Ok heres a very odd thing I discovered
> 
> I have upgrade to waybar-git for version 0.11
> 
> if I put the {} on the right, icon disappear.
> 
> if I put the {} on the left, icon stays
> 
> what an odd bug lmao

Oh yeah that is true. Well, I should close this issue then it might be fixed in the next update.

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/4f3d9f65bff6127dac11fcd997dd495863f3f905

I just put it on left as default for now...

**Comment by dwilliam62** [comment]
BTW on ARCO when I added the {} back in it failed as before  Moving the `{}`  to the left resolved it for me
