### ISSUE TITLE
bash interpreter in scripts

### ISSUE THREAD

**Issue by sgnoyke** [JaKooLit/Hyprland-Dots#44]
Please switch from `#!/bin/bash` to `#!/usr/bin/env bash` to set the interpreter in the first line for better compatibility in other operating systems for all .sh files. :)  ty!

**Comment by JaKooLit** [comment]
which distro you are using?

I use this on
Debian
Gentoo
Fedora
Arch
NixOS
OpenSUSE

and I dont use issues

**Comment by lentik** [comment]
Oh ok, ty for answering! I tried your dotfiles in NixOS and it seems to work, but scripts could not executed with #!/bin/bash, because there is no /bin/bash binary in NixOS. So for better compability it should be possible with `#!/usr/bin/env bash`

**Comment by JaKooLit** [comment]
you need this in nixos

services.envfs.enable = true;
