### ISSUE TITLE
[Bug]: After waybar update another icon is missing and flameshot doesn't show up in systray

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Hyprland-Dots#442]
## Bug Report
Arch (vanilla and arco)   Using the v2.3.6 dots the icon for networking is missing 

![image](https://github.com/user-attachments/assets/9f9b90c3-cf45-4c24-9d39-16f0456dadee)

### Description

You can see the place where it should be and if you hover over it or right mouse you get the info, so nm-applet is running 

### Steps to Reproduce
Update system, restart 
I tried restarting and changing the waybar theme and style 

### Additional Information

[diag.txt](https://github.com/user-attachments/files/17006380/diag.txt)

**Comment by dwilliam62** [comment]
Some one else just reported the same issue  Missing icons in the taskbar (systray I believe) 
![image](https://github.com/user-attachments/assets/511e5d9a-30fe-44a5-aae7-8bbdbc2ee483)

**Comment by dwilliam62** [comment]
![image](https://github.com/user-attachments/assets/fef286a8-802c-428d-b9ae-03de2f13f97a)

Confirming wabar 0.11 

 I copied the default lapto v3 and made a couple small edits.   Removed laptop related items and copied the systray to the center as well as a test.    Now the icons show up on both 
![Screenshot_15-Sep_12-04-19_22388](https://github.com/user-attachments/assets/3f89b0d5-f90e-4ee9-b059-4ca824c5db7c)

**Comment by dwilliam62** [comment]
But flameshot shows in systray on nixos 
![image](https://github.com/user-attachments/assets/767b29e7-20fe-4b53-8ecc-0c7ddbc2d832)

Which is the older waybar 

![Screenshot_15-Sep_12-06-05_10937](https://github.com/user-attachments/assets/5f08c2d8-14cc-47f5-b668-34b05479e4c9)

**Comment by JaKooLit** [comment]
https://github.com/Alexays/Waybar/pull/3604

**Comment by JaKooLit** [comment]
https://github.com/Alexays/Waybar/issues/3597

**Comment by JaKooLit** [comment]
I hope alexays will issue a new release

else will have to install the git version

**Comment by dwilliam62** [comment]
An update was just released that resolves it   :)
