### ISSUE TITLE
[Feature Request]: Add Window Rule for Thorium browser 

### ISSUE THREAD

**Issue by dwilliam62** [JaKooLit/Hyprland-Dots#448]
### Description
I have to add this in every update. ;)    

Maybe add some others as well  ? 
 
### Use Case
 

It's a popular browser 
### Proposed Solution
windowrulev2 = workspace 2, class:^([Tt]horium-browser)$

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/34d3c4f79d0b73deaffcfb2c12ec20fe3ba57fe2
