### ISSUE TITLE
Some feedback after use

### ISSUE THREAD

**Issue by punkucheung** [JaKooLit/Hyprland-Dots#457]
When opening the terminal kitty, how can I close the image in the upper left corner? Please answer. Thank you.

**Comment by darkeddie** [comment]
For the current session:
`clear`
Permanently:
Remove or comment out `pokemon-colorscripts --no-title -s -r` in ~/.zshrc and remove the package

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/wiki/FAQ#%EF%B8%8F-dont-like-pokemon-colorscripts
