### ISSUE TITLE
[Bug]: Link to discord in readme.md does not work

### ISSUE THREAD

**Issue by chrismcfee** [JaKooLit/Hyprland-Dots#468]
### Description

[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. Click on discord link: https://discord.gg/9JEgZsfhex
2. Invite Link Unable to accept invite

### Expected Behavior

Expected link to work

### Actual Behavior

Link did not work

### Screenshots

![image](https://github.com/user-attachments/assets/90cace43-802c-4850-9967-eb59e078a85c)

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```


```

or you can also run `inxi -CGIsSMnr >diag.txt` and attach diag.txt

### Additional Information

not a bug with the project really; just did not know where else to put this

**Comment by JaKooLit** [comment]
thank you for bringing this to my attention

can you try to click any of this buttons?

pls tell me if you experience same issue. I may need to renew it.

I have tested the link and it is working fine on my test.

![Screenshot_20241004_101016_Samsung Internet](https://github.com/user-attachments/assets/57826d7d-ab97-4726-a5ae-7569f429a098)

**Comment by chrismcfee** [comment]
yeah, it worked after I clicked it several times. might have been a problem with my discord (vesktop). sorry
