### ISSUE TITLE
[Bug]: Fedora dots .oh-my-zsh is empty

### ISSUE THREAD

**Issue by Topkack** [JaKooLit/Hyprland-Dots#470]
### Description
.oh-my-zsh folder is empty after install.
[Provide a clear and concise description of the bug.]

### Steps to Reproduce

1. [First Step] Install Fedora everything edition minimal install
2. [Second Step] Hand-type git clone into terminal
3. [and so on...]

### Expected Behavior

[What did you expect to happen?]

### Actual Behavior

[What actually happened?]

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```


```

or you can also run `inxi -CGIsSMnr >diag.txt` and attach diag.txt

### Additional Information

[Add any other information about the problem here. For example, you might include the error message, any recent changes that you made to the project, or any other relevant details.]

**Comment by JaKooLit** [comment]
cd Fedora-Hyprland
./install-scripts/zsh.sh

**Comment by JaKooLit** [comment]
closing as no reply received
