### ISSUE TITLE
Wlogout

### ISSUE THREAD

**Issue by skarpinis** [JaKooLit/Hyprland-Dots#472]
### Description

small and not smooth animations

### Steps to Reproduce

1. change resolution to 4k
2. change scaling 1.25 or 1.5
3. [and so on...]

### Expected Behavior

correct size and smooth animations.

### Actual Behavior

wrong size small weird looking and jittery animations.

**Comment by JaKooLit** [comment]
I dont have 4k monitor.

so pls play around the script located at

~/.config/hypr/scripts/wlogout.sh

line 7 & 8


if you dont want the animation, you can simply just remove all data, leaving just shebang and next line 
wlogout

**Comment by skarpinis** [comment]
any posibility adjust animation speed? only logout reduced fps or something...

**Comment by skarpinis** [comment]
was nvidia driver issue regard animation...

**Comment by ChemicalCarnivore** [comment]
What's the driver issue/how did you find it? I have choppy animations on 1440p scaled monitor with nvidia, want to check it's the same issue and see if I can find a workaround.

**Comment by dwilliam62** [comment]
> What's the driver issue/how did you find it? I have choppy animations on 1440p scaled monitor with nvidia, want to check it's the same issue and see if I can find a workaround.

I tested at 4K with AMD iGPU 790M and NVIDIA RTX3060 at 4K.  I don't see any chopiness.  There is the animation effect that makes the icon grow as you hover.  There is a small delay there but that's CSS   it's the same for both and on other systems at lower resolutions.  I tested at 1440 also

**Comment by ChemicalCarnivore** [comment]
> > What's the driver issue/how did you find it? I have choppy animations on 1440p scaled monitor with nvidia, want to check it's the same issue and see if I can find a workaround.
> 
> I tested at 4K with AMD iGPU 790M and NVIDIA RTX3060 at 4K. I don't see any chopiness. There is the animation effect that makes the icon grow as you hover. There is a small delay there but that's CSS it's the same for both and on other systems at lower resolutions. I tested at 1440 also

Is that using fractional scaling? It works fine for me at 1 but not at 1.25.

**Comment by dwilliam62** [comment]
I did not try it at 1.25.   You didn't mention that part.  I will see if I can try that later, but that makes it hyprland or NVIDIA issue.   You might have to adjust explicit sync values, etc.

**Comment by skarpinis** [comment]
On nvidia drivers 550 is not smooth animations but on 560 much better not perfect.

**Comment by dwilliam62** [comment]
I am running 560.35.03   Using Fedora 40

**Comment by ChemicalCarnivore** [comment]
This is what it looks like for me using 560.35.03 at 1.25 frac scaling

https://github.com/user-attachments/assets/f961e2a4-ccb5-44c3-b7f2-a7d31d06cd18
