### ISSUE TITLE
[Bug]: Broken on new hyprland version

### ISSUE THREAD

**Issue by nathblade16** [JaKooLit/Hyprland-Dots#485]
### Description

When I upgraded my system it installed a new version of hyprland, this broke the config

### Steps to Reproduce

1. Be on a rolling release distro (like arch linux)
2. Upgrade hyprland
3. Restart hyprland

### Expected Behavior

The config works and shows no errors

### Actual Behavior

It showed errors, a downgrade is required to fix

### Screenshots

![Uploading Screenshot_12-Nov_09-08-37_23951.png…]()

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
hyprland-0.45.0-1

```

or you can also run `inxi -CGIsSMnr >diag.txt` and attach diag.txt

### Additional Information

Please update the configs to support the new hyprland version, had to downgrade my hyprland

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/d31589183fb15b6de3e2f9ffd2b315563e7362aa


I dont know the error since screenshot is not uploaded..

But you must be talking about this?

In which I have already updated with this commit (more than a day ago)

**Comment by nathblade16** [comment]
> [d315891](https://github.com/JaKooLit/Hyprland-Dots/commit/d31589183fb15b6de3e2f9ffd2b315563e7362aa)
> 
> I dont know the error since screenshot is not uploaded..
> 
> But you must be talking about this?
> 
> In which I have already updated with this commit (more than a day ago)

weird, I tried updating from the main branch and there was no difference

**Comment by JaKooLit** [comment]
upload the error again so I can see

**Comment by nathblade16** [comment]
I will just quickly manually update the file and hyprland than I will

**Comment by nathblade16** [comment]
yeah the issue is fixed now, it happened because of some weird thing with the way I tried to update
