### ISSUE TITLE
[Bug]: Error with the dots on hyprland-git 0.45.0.r16.a29cfa78-1 

### ISSUE THREAD

**Issue by brockar** [JaKooLit/Hyprland-Dots#486]
### Description
It seems that certain configuration options related to "shadows" are unrecognized or missing. These options include:
```
    drop_shadow (line 22)
    shadow_range (line 23)
    shadow_render_power (line 24)
    col.shadow (line 26)
    col.shadow_inactive (line 27)
```
Maybe the names of these configurations changed in the latest version of Hyprland. For now, I just commented out those lines, and everything is working fine.  

### Steps to Reproduce
update hyprland-git to the latest version.
`yay -Syyu`

### Screenshots
![image](https://github.com/user-attachments/assets/ce009b2b-4cd2-4480-8a59-9790b5ee4fb6)

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
[diag.txt](https://github.com/user-attachments/files/17711067/diag.txt)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/d31589183fb15b6de3e2f9ffd2b315563e7362aa


pls update your dots to newer version or see thr update on this commit

**Comment by brockar** [comment]
I tried before creating the issue, but the method in the readme.md didn’t work. I didn’t think to check the commits earlier, sorry.
When I run the update, it says I'm on the latest version.
```
./upgrade.sh
[OK] No upgrade found. The installed version (v2.3.7) is up to date with the Hyprland-Dots version (v2.3.7).
```
