### ISSUE TITLE
[Feature Request]: Horizontal Flow for wallpaper selection

### ISSUE THREAD

**Issue by m0r4a** [JaKooLit/Hyprland-Dots#490]
### Description

Add the option flow: horizontal Wallpapers selection menu

This option makes rofi count images horizontally instead of vertically, which means that in practical terms, when there aren't enough elements to fill all columns and rows, it prioritizes having each row completely filled rather than trying to place an element in every row.

### Use Case

When searching for Wallpapers and few options are available, I think it looks better to prioritize filling rows first.

### Proposed Solution

In `config/rofi/config-wallpaper.rasi`

Change from:

```
listview {
  columns: 4;
  lines: 3;
}
```

To: 

```
listview {
  columns: 4;
  lines: 3;
  flow: horizontal;
}
```

#### Image of the setting disabled:
![flow_horizontal_disabled](https://github.com/user-attachments/assets/8e6f5f1f-7bb4-4737-888c-fb9562c487d7)

Image of the setting enabled: 
![flow_horizontal_enabled](https://github.com/user-attachments/assets/b10993c1-d621-4c6f-a428-c57406119ccd)

_Note: I'm sorry for the horrible colors, it's still a work in progress_

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/c3900285bcb30a5af49c638eb3c16bd43e2c2527

thanks
