### ISSUE TITLE
Issue with RainbowBorders.sh border colors script

### ISSUE THREAD

**Issue by m02bd0** [JaKooLit/Hyprland-Dots#495]
Hello,

I am facing an issue with the RainbowBorders.sh script that I use to change the border colors in Hyprland, where the color effects are not persistent after reloading the settings or changing the background. Below are the details of the problem:

The Problem:

Manual Script Execution: When I run the script manually, it works perfectly, changing the border colors of the active window.

Effect Stops After Background Change or hyprctl reload:

When I change the background, the effect disappears, and the border color returns to the default.

After running hyprctl reload to reload the settings, the effect stops as well.

Is there a way to ensure that the RainbowBorders.sh effect stays active permanently, even after changing the background or reloading the settings?

Is there a way to make the script run automatically every time the session starts or after settings are changed?

**Comment by JaKooLit** [comment]
https://www.reddit.com/r/hyprland/s/5xPwJTToKI

I answered that in Reddit

super shift R to reload

when you change something on Hyprland, hyprctl reload does not reload all startup apps

super shift R I created is to reload the Dots

**Comment by m02bd0** [comment]
> https://www.reddit.com/r/hyprland/s/5xPwJTToKI
> 
> I answered that in Reddit
> 
> super shift R to reload
> 
> when you change something on Hyprland, hyprctl reload does not reload all startup apps
> 
> super shift R I created is to reload the Dots

Sorry, I tried to implement this shortcut but it did not work. After changing the background, the script stops working

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/scripts/Refresh.sh

unless you changed something

the script above is to restart Rainbow borders script

**Comment by JaKooLit** [comment]
sorry, should be super alt R NOT super shift R

**Comment by m02bd0** [comment]
> sorry, should be super alt R NOT super shift R

 Super alt R works, but the script doesn't work

I remove it before and download it again in the same folder, but the script still doesn't work

**Comment by JaKooLit** [comment]
ah that explains

you need to make it executable

**Comment by m02bd0** [comment]
> ah that explains
> 
> you need to make it executable

I remove it before and download it again after script problem, anyway how can  i make it executable please?

**Comment by JaKooLit** [comment]
chmod +x ~/.config/hypr/UserScripts/RainbowBorders.sh

**Comment by m02bd0** [comment]
It solved, thanks a million for your script and everything else.
