### ISSUE TITLE
[Bug]: config.nix

### ISSUE THREAD

**Issue by R1YMOLIM** [JaKooLit/Hyprland-Dots#496]
Hello guys i'm get error config.nix
┌─[r1y@NixOS] - [~] - [Sat Dec 07, 23:50]
└─[$] <> sudo nixos-rebuild -I nixos-config=/home/r1y/NixOS-Hyprland/hosts/NixOS/config.nix switch             

building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin
         at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/lib/attrsets.nix:1574:11:
         1573|         || pred here (elemAt values 1) (head values) then
         1574|           head values
             |           ^
         1575|         else

       … while evaluating the attribute 'value'
         at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/lib/modules.nix:846:9:
          845|     in warnDeprecation opt //
          846|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          847|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `system.build.toplevel':

       … while evaluating definitions from `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `assertions':

       … while evaluating definitions from `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `systemd.services':

       … while evaluating definitions from `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/services/logging/logrotate.nix':

       … while evaluating the option `services.logrotate.enable':

       … while evaluating the option `users.groups':

       … while evaluating definitions from `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/config/resolvconf.nix':

       … while evaluating the option `networking.resolvconf.enable':

       … while evaluating the option `environment.etc':

       … while evaluating definitions from `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/nixos/modules/services/networking/ssh/sshd.nix':

       … while evaluating the option `users.users':

       … while evaluating definitions from `/home/r1y/NixOS-Hyprland/hosts/NixOS/users.nix':

       … while evaluating the module argument `username' in "/home/r1y/NixOS-Hyprland/hosts/NixOS/users.nix":

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'username' missing
       at /nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source/lib/modules.nix:515:28:
          514|         addErrorContext (context name)
          515|           (args.${name} or config._module.args.${name})
             |                            ^
          516|       ) (functionArgs f);

**Comment by dwilliam62** [comment]
I have no idea what you are trying to do there but a rebuild against the
config.nix makes no sense to me.

The rebuild should be against the flake.nix    sudo nixos-rebuild switch
--flake .#HOSTNAME

 So if you have made some major changes to his flake and config I had no
idea how to help you.

Don

**Comment by dwilliam62** [comment]
Did you get it working ?

**Comment by R1YMOLIM** [comment]
Yes, but when I download example alacritty, I can't find them

**Comment by R1YMOLIM** [comment]
Yes, thank you, I just didn't know how to use them, sorry to bother you.

**Comment by dwilliam62** [comment]
> Yes, thank you, I just didn't know how to use them, sorry to bother you.

 You are welcome!  No problem at all.   NIX/NIXOS can be very confusing!   There's a lot to learn, I am am far from being an  expert.  

Regards,
Don
