### ISSUE TITLE
[Feature Request]: Change Keybind for 

### ISSUE THREAD

**Issue by k4l1mi5t** [JaKooLit/Hyprland-Dots#499]
### Description

Change the keybind for showing Keybinds in Rofi to something other than $mainMod SHIFT + K, to prevent conflicts for users who want to remap moving of windows with vim motions keys like $mainMod SHIFT +  H/J/K/L.

### Use Case

Many vim users don't want to leave their keyboard or move their hands to the arrow keys, so rebinding these to the same keys as used within vim, makes alot of sense and is implemented across many tools. 

### Proposed Solution

Change the keybind which is not conflicting with vim motion keys (HJKL), such as E.

### Alternative Solution

Use any other key :)

### PS

Thanks alot for the great work!

**Comment by JaKooLit** [comment]
you can change your vim motions with

super ctrl combinations instead
