### ISSUE TITLE
[Bug]: Pyprland stopped working after an update.

### ISSUE THREAD

**Issue by daxisunder** [JaKooLit/Hyprland-Dots#505]
### Description

After an update pyprland stopped working (zoom and scratchpads), pypr daemon fails to start with the error message
`❯ pypr
/usr/lib/python3.13/site-packages/pyprland/plugins/scratchpads/objects.py:149: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior
  return await self.get_client_props(
/usr/lib/python3.13/site-packages/pyprland/plugins/scratchpads/objects.py:185: FutureWarning: functools.partial will be a method descriptor in future Python versions; wrap it in staticmethod() if you want to preserve the old behavior
  client_info = await self.get_client_props(addr=self.full_address, clients=clients)
[0.109] [glfw error 65544]: process_desktop_settings: failed with error: [org.freedesktop.DBus.Error.UnknownMethod] No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop`

### Steps to Reproduce

1. Try to use scratchpad or zoom function (doesn't work)
2. Start pypr daemon (it fails to start)

### Expected Behavior

MOD + z zooms the desktop, MOD + SHIFT + ENTER opens scratchpad

### Actual Behavior

Nothing, it doesn't work

**Comment by daxisunder** [comment]
Fixed it.

**Comment by JaKooLit** [comment]
how did you fixed it? Im guessing reinstalling pyprland fixed the issue?

**Comment by daxisunder** [comment]
> how did you fixed it? Im guessing reinstalling pyprland fixed the issue?

Reinstallig `pyprland` and restartyng `pypr` daemn.
