### ISSUE TITLE
[Bug]: Electron apps take a while to open

### ISSUE THREAD

**Issue by logslmao** [JaKooLit/Hyprland-Dots#506]
### Description

Electron apps take about 20 - 50 seconds to open, including Obsidian & VSCodium, This did not happen on my old hyprland dotfiles. The command runs within seconds, in the case of vscodium about 0.25, however the app does not open at all until that amount of time later

### Steps to Reproduce

Install an electron app or build it from source
Try to open it

### Expected Behavior

For the apps to open within 1- 2 seconds

### Actual Behavior

Apps took a large amount of time to open

### Screenshots

[If applicable, add screenshots to help explain your problem.]

### Environment

[Please add any other relevant information about the bug and remove the unnecessary lines.]

### show output of `inxi -CGIsSMnr` install package `inxi` if not exist
show output here
```
System:
  Host: realnamecensorpc Kernel: 6.12.4-arch1-1 arch: x86_64 bits: 64
  Desktop: Hyprland v: 0.45.2 Distro: Arch Linux
Machine:
  Type: Laptop System: HP product: Victus by HP Laptop 16-d1xxx v: N/A
    serial: <superuser required>
  Mobo: HP model: 8A26 v: 34.64 serial: <superuser required> UEFI: AMI
    v: F.14 date: 11/09/2023
CPU:
  Info: 14-core (6-mt/8-st) model: 12th Gen Intel Core i7-12700H bits: 64
    type: MST AMCP cache: L2: 11.5 MiB
  Speed (MHz): avg: 400 min/max: 400/4600:4700:3500 cores: 1: 400 2: 400
    3: 400 4: 400 5: 400 6: 400 7: 400 8: 400 9: 400 10: 400 11: 400 12: 400
    13: 400 14: 400 15: 400 16: 400 17: 400 18: 400 19: 400 20: 400
Graphics:
  Device-1: Intel Alder Lake-P GT2 [Iris Xe Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GA107M [GeForce RTX 3050 Ti Mobile] driver: nvidia
    v: 565.77
  Device-3: Luxvisions Innotech HP Wide Vision HD Camera driver: uvcvideo
    type: USB
  Display: wayland server: X.org v: 1.21.1.15 with: Xwayland v: 24.1.4
    compositor: Hyprland v: 0.45.2 driver: X: loaded: modesetting,nvidia
    dri: iris gpu: i915,nvidia resolution: 1920x1080
  API: EGL v: 1.5 drivers: iris,nvidia
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.6 vendor: nvidia v: 565.77
    renderer: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2
  API: Vulkan v: 1.4.303 drivers: N/A surfaces: xcb,xlib,wayland
Network:
  Device-1: MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter
    driver: mt7921e
  IF: wlp5s0 state: up mac: 14:13:33:c7:3b:db
  Device-2: Realtek RTL8111/8168/8211/8411 PCI Express Gigabit Ethernet
    driver: r8169
  IF: eno1 state: down mac: 84:69:93:57:5a:aa
  IF-ID-1: virbr0 state: down mac: 52:54:00:91:b2:e4
Sensors:
  System Temperatures: cpu: 57.2 C mobo: N/A
  Fan Speeds (rpm): cpu: 4007 fan-2: 4186
Repos:
  Active pacman repo servers in: /etc/pacman.d/mirrorlist
    1: https://at.arch.mirror.kescher.at/$repo/os/$arch
    2: https://de.arch.mirror.kescher.at/$repo/os/$arch
    3: https://mirror.theo546.fr/archlinux/$repo/os/$arch
    4: https://archlinux.thaller.ws/$repo/os/$arch
    5: https://arch.mirror.constant.com/$repo/os/$arch
    6: https://mirror.osbeck.com/archlinux/$repo/os/$arch
    7: https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
    8: https://london.mirror.pkgbuild.com/$repo/os/$arch
    9: https://mirror.sunred.org/archlinux/$repo/os/$arch
    10: https://arch.niranjan.co/$repo/os/$arch
    11: https://mirror.pseudoform.org/$repo/os/$arch
    12: https://america.mirror.pkgbuild.com/$repo/os/$arch
    13: https://md.mirrors.hacktegic.com/archlinux/$repo/os/$arch
    14: https://mirror.moson.org/arch/$repo/os/$arch
    15: https://mirror.ufscar.br/archlinux/$repo/os/$arch
    16: https://asia.mirror.pkgbuild.com/$repo/os/$arch
    17: https://seoul.mirror.pkgbuild.com/$repo/os/$arch
    18: https://sydney.mirror.pkgbuild.com/$repo/os/$arch
    19: https://repo.jing.rocks/archlinux/$repo/os/$arch
    20: https://us.arch.niranjan.co/$repo/os/$arch
Info:
  Memory: total: 16 GiB note: est. available: 15.28 GiB used: 4.6 GiB (30.1%)
  Processes: 373 Uptime: 1h 47m Shell: Zsh inxi: 3.3.36
```

### Additional Information

This is the full log of obsidian, as vscodium doesn't provide logs and i thought i should include this as after the final line it launches

```
2024-12-23 15:17:39 Loading main app package /usr/lib/obsidian/obsidian.asar
2024-12-23 15:17:40 Checking for update using Github
2024-12-23 15:17:40 Success.
2024-12-23 15:17:40 Latest version is 1.7.7
2024-12-23 15:17:40 App is up to date.
[18957:1223/151810.430888:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[18957:1223/151810.430965:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[18811:1223/151810.440729:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=512
[18957:1223/151840.895342:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[18811:1223/151840.905229:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=512
[18811:1223/151911.375261:ERROR:gpu_process_host.cc(1007)] GPU process exited unexpectedly: exit_code=512
[18957:1223/151911.822833:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

**Comment by logslmao** [comment]
It works now! TYSM!!!!

**Comment by dwilliam62** [comment]
> It works now! TYSM!!!!

You are very welcome!

**Comment by ValynTyler** [comment]
Would anybody be so kind as to explain how to do this? I have the same issue, though I am using different dotfiles. I can get obsidian to work by running `obsidian --disable-gpu`, but I would like it to also work when launched from my app picker. Does anyone know how to do this without disabling gpu acceleration system-wide?

**Comment by dwilliam62** [comment]
> Would anybody be so kind as to explain how to do this? I have the same issue, though I am using different dotfiles. I can get obsidian to work by running `obsidian --disable-gpu`, but I would like it to also work when launched from my app picker. Does anyone know how to do this without disabling gpu acceleration system-wide?

 You need to edit the app.desktop file to add the flag to disable GPU

**Comment by ValynTyler** [comment]
> This issue is not "Hyprland" but the version of electron these apps are using. they do not support wayland. They need to update their software

I see. This technically gets solved with time, right? Why though, is this not an issue on GNOME for instance? I'm not too familiar with the x11/wayland magic going on behind the scenes, but I'm assuming it's because GNOME uses the xserver and hyprland doesn't?

**Comment by dwilliam62** [comment]
> > This issue is not "Hyprland" but the version of electron these apps are using. they do not support wayland. They need to update their software
> 
> I see. This technically gets solved with time, right? Why though, is this not an issue on GNOME for instance? I'm not too familiar with the x11/wayland magic going on behind the scenes, but I'm assuming it's because GNOME uses the xserver and hyprland doesn't?

Re: Update.  One would hope and expect that yes.   Discord for example finally has a beta version that supports Wayland. 
 Another wrinkle is of course NVIDIA.   That has it's own set of challenges with Wayland and electron. 
 
 Correct standard GNOME issues X11 not Wayland.   Wayland doesn't run X11 in the background  It has compatibility layer called xwayland to handle native X11 apps

**Comment by ValynTyler** [comment]
I see. Thanks! That makes sense. I'm running NixOS on nvidia hardware and everything actually runs fine, so long as I don't acknowledge that I have a GPU.

**Comment by dwilliam62** [comment]
> I see. Thanks! That makes sense. I'm running NixOS on nvidia hardware and everything actually runs fine, so long as I don't acknowledge that I have a GPU.

I also use NIXOS w/AMD, intel,  and NVIDIA.  NIXOS is better than just about any Linux OS when it comes to NVIDIA  IMO  

Though I am sticking with 24.11  Got tired of all the updates in unstable.

**Comment by dwilliam62** [comment]
> So do you also deal with these issues? How do you run your electron apps? Or do you not use any?

 i try to limit electron apps as much as possible   Use flatpaks for example.   Thorium for example doesn't seem to have issues vs. Chromium  Or disable GPU where needed when I can't.   Also some like google and thorium have better support for wayland  it needs to be enabled
