### ISSUE TITLE
Hyprland moved to oklab for colors

### ISSUE THREAD

**Issue by LeeTalbert** [JaKooLit/Hyprland-Dots#510]
### Description
The most recent hyprland update moved to oklab for colors instead of srgb.  

### Steps to Reproduce
1. Update to hyprland 0.46.2
2. 
3. Profit.........I mean.....colors broke

### Expected Behavior
Pretty colors

### Actual Behavior
No pretty colors

### Screenshots
too lazy

### Additional Information
Config error in file /home/user/.config/hypr/UserConfigs/UserSettings.conf at line 31 : Error parsing gradient rgb(151519)Col as a color

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/issues/500
