### ISSUE TITLE
Improment of RofiBeats without paywall with features 

### ISSUE THREAD

**Issue by S4NKALP** [JaKooLit/Hyprland-Dots#56]
![RofiMusic](https://github.com/JaKooLit/Hyprland-Dots/assets/98226895/2ee76697-7780-4571-9b8a-6c197a4212c4)
![RofiMusicControl](https://github.com/JaKooLit/Hyprland-Dots/assets/98226895/f07bb38c-156a-4397-9cba-e1f071c894b0)

Feature
* Stop the music
* Play Next & Previous Track from playlist
* Pause/Resume Music
* Increase/Decrease Volume of MPV

# why I don't use paywall
* according to my taste it is useless

<b> mpv-mpris is needed dependency which help to detect mpv player by playerctl  [Script Link](https://github.com/S4NKALP/hyprland/blob/main/config/hypr/scripts/RofiMusic.sh) </b>
<b> some other scripts can be found in my repository  [my hypr config](https://github.com/S4NKALP/hyprland) </b>

<b> Sorry for my grammer and poor English 😅 </b>

**Comment by JaKooLit** [comment]
thanks for sharing for rofi beats... I can integrate some items...

regarding pywal, it all depends on implementation...

**Comment by JaKooLit** [comment]
added mpv-mpris but I approach differently :) Thanks for the ideas :)

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/releases/tag/v2.1.18
