### ISSUE TITLE
Keyring not working after installing on Fedora

### ISSUE THREAD

**Issue by enneaccatre** [JaKooLit/Hyprland-Dots#68]
Hello, after installing Hyprland-Dots using the script I got an error message about the keyring and the password manager on google chrome is not working anymore

**Comment by JaKooLit** [comment]
did you install Fedora-Hyprland or just straight to Hyprland-Dots?

**Comment by JaKooLit** [comment]
whats the update on this?

**Comment by JaKooLit** [comment]
closing as no update.. guessing maybe completed...
