### ISSUE TITLE
When clicked on dunst action (A) notification it opens "Unsure what to show" screen

### ISSUE THREAD

**Issue by SherLock707** [JaKooLit/Hyprland-Dots#89]
The following Rofi menu is shown when left clicked on a Dunst action notification:
![image](https://github.com/JaKooLit/Hyprland-Dots/assets/26952545/a1368425-bd02-4bfb-8aa4-0a5a0f3ee5ea)

_Notification received over KDE connect._

**Comment by SherLock707** [comment]
OS: Arch (Garuda Linux x86_64)
Kernel: 6.6.7-zen1-1-zen
Display (LG HDR WQHD): 3440x1440 @ 75Hz
WM: Hyprland (Wayland)
Theme: Catppuccin-Mocha-Standard-Mauve-Dark [GTK2/3], Sweet-Dark [GTK4]
CPU: 13th Gen Intel(R) Core(TM) i5-13500 (20) @ 4.80 GHz
GPU: AMD Radeon RX 6700 XT
Memory: 16 GB
FS: Btrfs

**Comment by JaKooLit** [comment]
huh.. I thought I have already changed that.. oh well

edit ~/.config/dunst/dunstrc

line 173
dmenu = /usr/bin/rofi -dmenu -p dunst

change to that one above

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Hyprland-Dots/commit/ff0733ec97d85270ab399259695ede86df47d1a8

**Comment by SherLock707** [comment]
Thanks a lot! I liked your previous power menu with Rofi better so had pulled and merged, may be I messed up there.
Thanks again for your great work.

**Comment by JaKooLit** [comment]
No Ived checked the one on repo and it wasnt corrected... you can pull from the releases the rofi power.. Unfortunately, rofi power is difficult to scale with different resolution hence I dropped that one
